facebook/componentkit

ComponentKit.podspec
README.md

Switch to public Travis CI

---

README.md

By the way I already signed the CLA  :)

Link CONTRIBUTING file in README

---

README.md

Add "ComponentKit" heading to README

---

ComponentKit/Core/CKComponent.h

Fix typo in CKComponent docblock

---

_docs/component-actions.md

Fixes a broken link in the docs.

Fix broken link

---

ComponentKit/DataSources/Common/CKComponentPreparationQueue.h
ComponentKit/DataSources/Common/CKComponentPreparationQueue.mm

- Protection against a nil callback block
- Add a not designated initializer assert

Add defensive code to the preparation queue

---

ComponentKit/DataSources/CKCollectionViewDataSource.mm
ComponentKit/DataSources/CKCollectionViewDataSourceCell.h
ComponentKit/DataSources/CKCollectionViewDataSourceCell.m
ComponentKit/HostingView/CKComponentHostingView.mm
ComponentKit/HostingView/CKComponentRootView.h
ComponentKit/HostingView/CKComponentRootView.m
ComponentKit/HostingView/CKComponentRootViewInternal.h

Closes facebook/componentkit#31

Expose a common root view for ComponentKit views; allow hitTest overrides

---

_docs/datasource-overview.md

Small doc typo

---

ComponentKit/DataSources/CKComponentBoundsAnimation+UICollectionView.mm

We were assuming every section had items, but this isn't true.

Fix out-of-bounds bug with component bounds animation

---

ComponentKit/Utilities/CKComponentAction.h
ComponentKit/Utilities/CKComponentAction.mm

This allows looking up e.g. which link was tapped on a text component.

Send the UIEvent as the context of CKComponentActionAttribute

---

_docs/state.md

Missing instructions to import CKComponentSubclass.h

Missing instructions

---

_docs/getting-started.md

For those unfamiliar with the "pod" command, this adds relevant info about setting up a pre-requisite.

Update getting-started.md to include link to CocoaPods

---

ComponentKit/DataSources/CKCollectionViewDataSource.h
ComponentKit/DataSources/CKCollectionViewDataSource.mm
Examples/WildeGuess/WildeGuess/WildeGuessCollectionViewController.mm

Test Plan: add `componentTreeWillAppear` in the sample app and verify it's called.

Actually announce tree events to listeners. Fixes #65.

---

_docs/philosophy.md

Fix spelling error

---

ComponentKit/Core/CKComponentBoundsAnimation.h
ComponentKit/Core/CKComponentBoundsAnimation.mm
ComponentKit/Core/CKComponentLifecycleManager.mm
ComponentKit/Core/ComponentViewManager.mm
ComponentKit/DataSources/CKComponentBoundsAnimation+UICollectionView.mm

Bounds animation now apply to subview bounds, not just top-level collection view changes.

Bounds animation

---

ComponentKit/DataSources/CKCollectionViewDataSource.mm

Turns out it is not needed with this implementation of the datasource.

[CVDS] Remove changeset regulator

---

ComponentKit/Core/Scope/CKComponentScopeHandle.mm
ComponentKit/Core/Scope/CKComponentScopeRoot.mm

Just some meaningless cleanup of types.

Clean up typing

---

ComponentKitTests/TransactionalDataSource/CKTransactionalComponentDataSourceUpdateStateModificationTests.mm

Insert missing tearDown call

---

ComponentKit/Core/Scope/CKComponentScopeRoot.mm

It's annoying that we need to do this, but such is life with C++.

Work around the static destructor fiasco by using a pointer

---

ComponentKit/Core/CKDimension.h
ComponentKit/Core/CKDimension.mm
ComponentKit/Core/CKSizeRange.h
ComponentKit/Core/CKSizeRange.mm
ComponentKit/Core/ComponentLayoutContext.h
ComponentKit/Core/ComponentLayoutContext.mm

Make CKRelativeDimension ctors inlineable

---

README.md

ComponentKit podfile should point to the latest version, 0.12

ReadMe ComponentKit Podfile is outdated

---

ComponentKit/Utilities/CKArrayControllerChangeset.h
ComponentKit/Utilities/CKArrayControllerChangeset.mm
ComponentKit/Utilities/CKSectionedArrayController.mm
ComponentKitTests/CKArrayControllerChangesetTests.mm
ComponentKitTests/CKSectionedArrayControllerTests.mm

This class is completely unnecessary.

[CDS] removed CKArrayControllerOutputPair

---

ComponentKit/DataSources/Common/CKComponentDataSource.mm
ComponentKit/DataSources/Common/CKComponentDataSourceInternal.h

Exposing the PreparationQueue concurrentQueue for cpu reprioritization

exposing concurrent queues for cpu prioritization

---

ComponentKit/Core/CKComponentLayout.mm
ComponentKit/Core/CKComponentLifecycleManager.mm
ComponentKitTests/CKComponentMountTests.mm

Fix responder chain for components mounted with CKMountComponentLayout()

---

ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceState.h
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceState.m

Will conflict with the enumerator for CKComponentDataSource otherwise.

CKComponentDataSourceEnumerator -> CKTransactionalComponentDataSourceEnumerator

---

ComponentKit/Core/ComponentMountContext.h

Since bleed-out has been simplified, this can be simplified too.

Simplify ComponentMountContext

---

ComponentKit/Core/CKComponent.mm
ComponentKit/Core/CKComponentController.mm
ComponentKit/Core/CKComponentSubclass.h
ComponentKit/Core/Scope/CKComponentScopeHandle.mm
ComponentKitTests/Scope/CKStateScopeComponentBuilderTests.mm

Once this is pulled, I'll update the relevant docs

Adding animationsOnInitialMount

---

ComponentKit/Core/CKComponentLayout.h
ComponentKit/Core/CKComponentLayout.mm
ComponentKit/Core/CKComponentLifecycleManager.mm
ComponentKitApplicationTests/CKComponentActionAttributeTests.mm
ComponentKitApplicationTests/CKComponentBoundsAnimationTests.mm
ComponentKitTests/CKComponentActionTests.mm
ComponentKitTests/CKComponentDelegateAttributeTests.mm
ComponentKitTests/CKComponentMountTests.mm

No more set arithmetic required to use component mounting.

Improve the mount/unmount APIs

---

ComponentKit/Core/CKComponentSize.h
ComponentKit/Core/CKComponentSize.mm
ComponentKit/Core/CKComponentViewAttribute.h
ComponentKit/Core/CKComponentViewConfiguration.h
ComponentKit/Core/CKComponentViewConfiguration.mm
ComponentKit/Core/CKDimension.h
ComponentKit/Core/CKDimension.mm
ComponentKit/Core/CKSizeRange.h
ComponentKit/Core/CKSizeRange.mm
ComponentKit/Utilities/CKEqualityHashHelpers.h
ComponentKit/Utilities/CKEqualityHashHelpers.mm

Needed to memoize on them, will not compile until memoization diff lands.
Fixes #285

Add hashing functions to core component things

---

ComponentKit/Core/CKComponent.mm
ComponentKit/Core/CKComponentInternal.h
ComponentKit/Core/CKComponentMemoizer.h
ComponentKit/Core/CKComponentMemoizer.mm
ComponentKit/Core/CKComponentSubclass.h
ComponentKitTests/CKComponentMemoizerTests.mm

This is the second half of the earlier memoization PR. 
Depends on https://github.com/facebook/componentkit/pull/269

Add opt-in memoization of component layout

---

_docs/datasource-basics.md

This is a very minor edit to the collection view documentation. I've fixed the UIKit lifecycle API usage and a typo.

fixed code samples in collection view documentation

---

ComponentKit/StatefulViews/CKStatefulViewComponentController.h
ComponentKit/StatefulViews/CKStatefulViewComponentController.mm
ComponentKit/StatefulViews/CKStatefulViewReusePool.mm
ComponentKitTests/StatefulViews/CKStatefulViewReusePoolTests.mm

... to a value defined by the CKStatefulViewComponentController class. Add related
unit test.

Add support for capping the maximum size of the stateful view reuse pool

---

ComponentKit/DataSources/Common/CKComponentDataSourceAttachController.mm

[CKCTDS] Fix silly CKComponentDataSourceAttachController bug

---

ComponentKit/Debug/CKComponentDebugController.mm

+ Previously dcomponents looked for a lifecycleManager but since componentkit is currently transitioning away from this and towards using CKComponentHostingView, dcomponents no longer worked in certain cases.
+ This pull request introduces a fix for those cases where a lifecycleManager does not exist but a CKComponentHostingView does.
The way the fix works is that if there is a CKComponentHostingView, this DebugController calls setNeedsLayout on the CKComponentHostingView. This may not be the best way to do this. @adamjernst may know a better one.

Fixed dcomponents to work with CKComponentHostingView

---

ComponentKit/DataSources/CKComponentBoundsAnimation+UICollectionView.mm

During large bounds change animations (such as for large inline expansion collapses) the user completely loses context. The fix is to adjust the content offset of the collection view by an appropriate amount to keep sufficient context.
The user gets his sense of context/place from the 'element taking up the most screen real-estate prior to animation'. After the animation completes the user should -
a) see this element on screen
b) see this element take up as much screen real-estate as it was taking up previously. (as close as possible given its bounds may have changed)
This fix should work for horizontal/vertical scrolling collection views.

CollectionView maintain context during large bounds change animation

---

ComponentKit/ComponentKit.h

Add import CKCollectionViewTransactionalDataSource in ComponentKit.h to use CKCollectionViewTransactionalDataSource

import CKCollectionViewTransactionalDataSource

---

_docs/animation.md

- Added `animationsOnInitialMount` description and code sample
- Added note about concurrent bounds and component animations
Related to @abhinav24's work in PR #267.

Added animationsOnInitialMount

---

ComponentKit/Core/CKComponentController.mm

Retaining animations on CKComponentController causes a reference cycle:
the component is retained by the animation, which is retained by the
controller, which is retained by the scope handle, which is retained by
the component.
The cycle gets broken when the component is unmounted, but that happens
too late in some cases. This change makes the cycle get broken when the
animation finishes.

Fix animation leaks

---

ComponentTextKit/TextKit/CKTextKitRenderer.h

For Sanity. ;)

---

ComponentKit/DataSources/Common/CKComponentDataSourceAttachController.mm

Understanding where `CKComponentDataSource` will be deallocated isn't always easy, especially in systems doing a lot of work on background dispatch queues. Let's loosen the restriction of keeping `CKComponentDataSourceAttachController` affined to the main thread by lifting the requirement in `-[CKComponentDataSourceAttachController dealloc]`.

Remove the main thread affinity requirement when tearing down the CKComponentDataSourceAttachController

---

ComponentKit.podspec
ComponentKitTestLib/ComponentKitTestLib.podspec
ComponentSnapshotTestCase/ComponentSnapshotTestCase.podspec
Examples/WildeGuess/Podfile.lock
Podfile.lock
README.md

Version 0.14

---

ComponentKit/DataSources/Common/CKComponentDataSourceAttachController.mm

This should have been removed in #462.

Remove unused CKComponentDataSourceAttachController helper method

---

ComponentKit/DataSources/CKCollectionViewTransactionalDataSource.h

Super simple, just ran into this in passing

Fixes typo in documentation

---

ComponentKit/DataSources/CKCollectionViewTransactionalDataSource.h
ComponentKit/DataSources/CKCollectionViewTransactionalDataSource.mm

As discussed in https://github.com/facebook/componentkit/pull/410, this is the actual error that should be fixed. The other is our own integration problem.
Thanks!

Weak supplementary view

---

ComponentTextKit/Utility/CKAsyncTransactionGroup.h
ComponentTextKit/Utility/CKAsyncTransactionGroup.m

Gets us closer to closing #390

Remove unused flush feature from CKAsyncTransactionGroup

---

ComponentTextKit/Utility/CKAsyncTransactionContainer.m
ComponentTextKit/Utility/CKAsyncTransactionGroup.h
ComponentTextKit/Utility/CKAsyncTransactionGroup.m

It's actually no longer necessary after I removed flushing in an earlier change.

Remove the removeTransactionContainer: API

---

ComponentKit/Debug/CKComponentHierarchyDebugHelper.h

This is a follow up to #534 that should help us close out #390.

Mark remaining APIs unsafe in extensions

---

ComponentTextKit/CKTextComponentLayer.mm

Previously it always rendered async - it should respect the displayMode as this change will let it do

Properly support sync display in TextComponentLayer

---

ComponentKit.xcodeproj/project.pbxproj
ComponentTextKit/CKLabelComponent.mm
ComponentTextKit/CKTextComponent.h
ComponentTextKit/CKTextComponent.mm
ComponentTextKitApplicationTests/CKTextComponentTests.mm

This should be exposed to give developers the ability to control async rendering more finely
For some reason updating https://github.com/facebook/componentkit/pull/556 is giving me trouble so making a new one

[CK] Add async render mode to CKTextComponent

---

ComponentKit/Core/ComponentUtilities.h
ComponentKitTests/CKVectorHelperTests.mm

Switching between git and hg, didn't stage the files before trying to commit the changes...smh CC/ @adamjernst

Fixes chaining

---

_docs/01-getting-started.md

Remove the "pod install" instruction in docs

---

ComponentKit/DataSources/CKComponentBoundsAnimation+UICollectionView.mm

This extends the component bounds animation so it considers the headers
or footers of the collection view as well. I changed the existing
implementation to use `layoutAttributesForElementsInRect:` rather than
`indexPathsForVisibleItems` and `layoutAttributesForItemAtIndexPath:`.
This makes it a little easier to retrieve layout attributes for
offscreen cells (you just extend the rect) and also works for
supplementary views without resorting to iOS9 specific APIs like
`visibleSupplementaryViewsOfKind:`.

Consider supplementary views in collection view bounds animation

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/Utilities/CKArrayControllerChangesetVerification.h
ComponentKit/Utilities/CKArrayControllerChangesetVerification.mm
ComponentKitTests/CKArrayControllerChangesetVerificationTests.mm

This will be used in CKSectionedArrayController

Added function to verify validity of changeset

---

_docs/09-component-actions.md

Note that CKComponentActionSend must be called on main thread

---

ComponentKit/HostingView/CKComponentHostingView.mm

Bonus is that with this we know what the issue was with the unmounting. So I get to remove the protections we added to CKComponent to guard against re-entrant mounting.

Prevent re-entrant component mounting in component hosting view

---

ComponentKit.xcodeproj/project.pbxproj

Add CKArrayControllerChangesetVerification to the ComponentKitAppleTV target

---

ComponentKit.podspec

I think this is all that needs to be done to support tvOS in the Podspec. I'll need to do a bit of testing to confirm though.

Add tvOS as a deployment target to the Podspec

---

ComponentKit.podspec

Releasing 0.15.1 to address two known tvOS issues (#630 and #631).

Version 0.15.1

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/Utilities/CKComponentContextHelper.h
ComponentKit/Utilities/CKComponentContextHelper.mm
ComponentKitTests/CKComponentContextTests.mm

This could be used to implement a system that bridges component context into some other language.

Add function to fetch all CKComponentContext items.

---

ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceConfiguration.mm

This assert isn't providing any meaningful signal.

Remove the work thread override assert

---

_docs/24-avoid-local-variables.md

Mention adding const explicitly

Update docs on avoiding local variables to mention const

---

_docs/12-component-controllers.md

Since we added the new `-initWithComponent:` we should document it
Attached is a screenshot of the changed section:
/cc @ocrickard

Update docs on component to controller data flow

---

static/componentkit.css

Fixes alignment when the nav has long titles.

Add width to nav

---

_docs/09-component-actions.md

We updated the API without updating the docs.

Update docs for typed component actions

---

.travis.yml
build.sh

Let's see if upgrading Xcode helps improve Travis CI reliability.

Upgrade Travis CI to Xcode 8.1

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/Utilities/CKComponentAction.h
ComponentKit/Utilities/CKComponentAction.mm
ComponentKitTests/CKComponentAccessibilityCustomActionsAttributeTests.mm

We use this in [Workflow](https://workflow.is) to make our components accessible.
Let me know what you think about the API or implementation!

Add ability to add custom accessibility actions to components

---

ComponentKit/Core/CKComponentBoundsAnimation.h
ComponentKit/HostingView/CKComponentHostingView.mm

Pretty self-explanatory! Let me know if there are any changes I need to make.

Add support for CKComponentBoundsAnimation to CKComponentHostingView

---

ComponentKit/ComponentKit.h

Are there any others that I am missing?

Update umbrella header with missing components

---

ComponentKit/StatefulViews/CKStatefulViewComponentController.mm
ComponentKit/StatefulViews/CKStatefulViewReusePool.h
ComponentKit/StatefulViews/CKStatefulViewReusePool.mm
ComponentKitTests/StatefulViews/CKStatefulViewReusePoolTests.mm

Reverts https://github.com/facebook/componentkit/pull/710, and adds back in https://github.com/facebook/componentkit/pull/709/files, which should fix the issues.

Bring back the pending reuse pool

---

ComponentKit/StatefulViews/CKStatefulViewComponentController.mm

@conradev this is my stab at fixing the issue you reported. Mind patching it and testing if it fixes your issue?

Speculative fix for duplicate stateful views in reuse pool

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/Core/Scope/CKDetectComponentScopeCollisions.h
ComponentKit/Core/Scope/CKDetectComponentScopeCollisions.mm
ComponentKitTests/Scope/CKDetectComponentScopeCollisionsTests.mm

Also adding tests for the scope component collisions

Report lowest common ancestor on scope component collisions.

---

ComponentKit/Components/CKButtonComponent.h
ComponentKit/Components/CKButtonComponent.mm
ComponentKit/Utilities/CKComponentAction.h
ComponentKit/Utilities/CKComponentAction.mm
ComponentKit/Utilities/CKComponentGestureActions.mm
ComponentKit/Utilities/CKComponentGestureActionsInternal.h

Reduces binary size and is a little faster.

Pass actions by reference

---

ComponentKit/Core/CKComponent.mm
ComponentKit/Core/CKComponentSubclass.h
ComponentKit/Core/CKUpdateMode.h
ComponentKit/Core/Scope/CKComponentScopeHandle.h
ComponentKit/Core/Scope/CKComponentScopeHandle.mm
ComponentKit/Core/Scope/CKComponentScopeRoot.h
ComponentKitTestHelpers/CKComponentLifecycleTestController.mm

Minor documentation improvements and code clean up from #749.

State update documentation improvements and clean up

---

ComponentKit/DataSources/Common/CKComponentDataSourceAttachController.h
ComponentKit/DataSources/Common/CKComponentDataSourceAttachController.mm

Just going through the small items on my personal TODO list.

Clean up CKComponentDataSourceAttachController a bit

---

ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSource.mm
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceChangeset.mm
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceItem.mm
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceState.mm

^^ so that when they print in logs its easier to decipher

[componentkit] make descriptions more readable for debugging

---

ComponentKit/Utilities/CKComponentContextHelper.h
ComponentKit/Utilities/CKComponentContextHelper.mm
ComponentKitTests/CKComponentContextTests.mm

Just do the easiest possible implementation here. Useful utility.

Provide a way to compare CKComponentContextContents objects

---

ComponentKit/Core/CKComponent.mm
ComponentKit/Core/Scope/CKComponentScope.h
ComponentKit/Core/Scope/CKComponentScope.mm
ComponentKit/Core/Scope/CKComponentScopeHandle.h
ComponentKit/Core/Scope/CKComponentScopeHandle.mm
ComponentKit/Core/Scope/CKComponentScopeRoot.h
ComponentKit/HostingView/CKComponentHostingView.mm
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSource.mm
ComponentKitTestHelpers/CKComponentLifecycleTestController.mm
ComponentKitTests/TransactionalDataSource/CKTransactionalComponentDataSourceUpdateStateModificationTests.mm

We want to expose this for some internal projects.

Add userInfo to state updates, announce via CKComponentStateListener

---

ComponentKit/Core/CKComponent.h
ComponentKit/Utilities/CKComponentAction.mm

This is already imported `CKComponentInteral` and is causing landing problems internally (for me)

Fix duplicate import

---

ComponentKit/Core/Scope/CKComponentScopeFrame.mm

On second thought, this is dangerous:
http://stackoverflow.com/questions/1934580/is-comparing-a-bool-against-yes-dangerous

Don't compare to YES explicitly

---

ComponentKit/Core/Scope/CKComponentScopeRoot.mm
ComponentKitTests/Scope/CKComponentScopeTests.mm

Currently, if we register the same component or controller twice (which could happen in certain cases when a new scope handle is created before the controller is resolved?), appearance callbacks will be invoked twice. Fix this by using a `NSHashTable` to store the component/controller.

Use NSHashTable to avoid registering duplicate component/controller

---

ComponentKit/Core/Scope/CKComponentScopeRootFactory.h
ComponentKit/Core/Scope/CKComponentScopeRootFactory.mm
ComponentKit/HostingView/CKComponentHostingView.h
ComponentKit/HostingView/CKComponentHostingView.mm
ComponentKit/HostingView/CKComponentHostingViewInternal.h
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceConfiguration.mm
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceConfigurationInternal.h
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceChangesetModification.mm
ComponentKitTests/Scope/CKComponentScopeTests.mm

Adds ability to leverage the scope root predicates from outside the framework.

Extend the use of the scope root predicates

---

ComponentKit/Core/ComponentUtilities.h
ComponentKitTests/CKVectorHelperTests.mm

No one uses the predicate, so remove it.

Simplify intersperse

---

ComponentKit/Core/ComponentUtilities.h

Fix docs for intersperse after #833

---

_docs/08-responder-chain.md

Change component-actions.html to actions.html.

Fix link to actions in Responder Chain page

---

_docs/01-getting-started.md

Update Getting Started steps

---

_docs/17-datasource-basics.md

Updated the section about `CKCollectionViewDataSource` in the basic page

[CK] Update CKCollectionViewDataSource documentation

---

_docs/17-datasource-basics.md

The indentation looks incorrect on our website. Hopefully this PR fixes it.

[CK] Update docs for CKCollectionViewDataSource (indentation)

---

_docs/01-getting-started.md

Note that carthage checkout only works in the source directory; fixed flow.

Getting Started fix for carthage checkout

---

_docs/09-actions.md

Replace `CKComponentActionSend` with the updated `CKActionSend` in the `Actions` document.

Update CKAction documentation.

---

README.md

Our mission at [Meta Open Source](https://opensource.fb.com/) is to empower communities through open source, and we believe that it means building a welcoming and safe environment for all. As a part of this work, we are adding this banner in support for Ukraine during this crisis.

docs: Adding social GH button
