ComponentTextKit/TextKit/CKTextKitRendererCache.h

This didn’t need to be const and the new version of the compiler was
complaining.
Should fix https://github.com/facebook/componentkit/issues/1

[componentkit] Fix TextKit build issues in Xcode 6.3

---

_docs/getting-started.md

The ‘Getting Started’ instructions were having users clone over SSH which would result in an error if one doesn’t have the proper access rights:
```
❯ git clone git@github.com:facebook/componentkit.git
Cloning into 'componentkit'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
Switching over to HTTPS is just an easier sane default.
ComponentKit looks super awesome! I’ve been anticipating checking it out for some time, so I’m excited!

Change instructions to clone over HTTPS [minor]

---

Examples/WildeGuess/WildeGuess/WildeGuessCollectionViewController.mm

A few fixes to the sample app. 
For counts, best to have them as a multiple of 4 for fetching as that ensures a uniform quote feed.

Fixes for WildeGuess

---

Examples/WildeGuess/WildeGuess/Images.xcassets/AppIcon.appiconset/Contents.json

Xcode shows warnings for missing icons files for Example project.
I've cleaned up Assets and fixed those warnings.
Those changes are done by Xcode, auto generated not by hand, so the are safe.

Remove Example project warnings

---

ComponentKit/HostingView/CKComponentHostingView.mm
ComponentKit/HostingView/CKComponentHostingViewInternal.h
ComponentKitTests/CKComponentHostingViewTests.mm

This cleans up internal APIs in the hosting view. None of this is external API, so it shouldn't break any existing code.

Clean up some cruft in CKComponentHostingView

---

ComponentKit.podspec
ComponentKit/Components/CKButtonComponent.mm
Examples/WildeGuess/Podfile.lock
Podfile.lock

ComponentKit intentionally uses the deprecated method sizeWithFont: to match UIButton's sizing logic. However, some projects are configured to treat warnings as errors, so let's squash this warning and treat any warnings as errors.

Silence warnings related to sizeWithFont

---

ComponentKit/Core/CKComponentAnimation.mm

These asserts will catch animations that don't have a component to animate or a `CAAnimation` to apply.

Two new asserts to catch invalid animations

---

ComponentKit/HostingView/CKComponentRootViewInternal.h

If we want to support non-CKComponentRootViews that use these hooks, it has to be a generic UIView.

Change type of view passed to hit test hooks

---

ComponentKit/Core/CKComponentController.mm

Instead of putting the state's numeric value in the assert, provide the state's name.
Yes, I hit one of these :)

Make unknown state assertions more convenient

---

Examples/WildeGuess/WildeGuess/WildeGuessCollectionViewController.mm

WildeGuessCollectionViewController have to conform not just to the UIScrollViewDelegate, but to its subclass UICollectionViewDelegateFlowLayout. It's not declared such yet (even that the example project compiles).
This also fixes one typo in a delegate name.

[WildeGuess] Explicitely declare conformance to UICollectionViewDelegateFlowLayout

---

ComponentKit/Core/CKComponentViewConfiguration.h

We need this internally to provide easier transition to the function based constructor for CKComponentViewClass. This change will be followed by removal of the block based constructor in the near future.

[CKComponentViewClass] add friend class for FB internal needs

---

ComponentTextKit/CKTextComponentLayer.mm

Fixes https://github.com/facebook/componentkit/issues/73
Turns out CKAsyncLayer doesn't fill opaque contexts when it's rendering synchronously, only when it's rendering asynchronously.  This overrides the standard drawInContext method and fills in the background color for CKAsyncLayer before it uses its normal rendering functions.

Fix black backgrounds in synchronously-rendered opaque text layers

---

ComponentKit/Core/CKComponentLifecycleManager.h
ComponentKit/Core/CKComponentLifecycleManager.mm
ComponentKit/HostingView/CKComponentHostingView.mm

Currently, calling `-sizeThatFits:` on a `CKComponentHostingView` will break component state. This is because `-sizeThatFits:` calls `-prepareForUpdateWithModel:`, which [modifies an internal state "cache"](https://github.com/facebook/componentkit/blob/b74ebfb788216103711f19247895e83f8206e7c5/ComponentKit/Core/CKComponentLifecycleManager.mm#L97).
This pull request adds a pure layout method on `CKComponentLifecycleManager`, which can be called any number of times without side effects.

Add pure -layoutForModel: method to CKComponentLifecycleManager

---

ComponentKit.podspec
Examples/WildeGuess/Podfile.lock
Podfile.lock

CocoaPods doesn't scope these flags to the pod

Remove 'treat warnings as errors' flag

---

ComponentKit/LayoutComponents/CKStackUnpositionedLayout.mm

Xcode 6.3 has more strict rules for compile errors. Make ComponentKit compile with the new version.
Compiled the project.

Fix a compile error in Xcode 6.3 - use fabs

---

_docs/advanced-views.md

Updated the example so that a UIView is returned, rather than the custom class, this ensures issue #106 is avoided.

Update advanced-views.md example

---

ComponentKit/DataSources/Common/CKComponentConstantDecider.m
ComponentKit/DataSources/Common/CKComponentDeciding.h

Unused and just brings more overhead to the implementation of CKComponentDeciding.

Remove reason from CKComponentDeciding

---

ComponentKit/Core/CKComponentLifecycleManager.h
ComponentKit/Core/CKComponentLifecycleManager.mm
ComponentKit/Core/Scope/CKComponentScopeFrame.h
ComponentKit/Core/Scope/CKComponentScopeFrame.mm
ComponentKitTests/CKComponentLifecycleManagerTests.mm

This removes cruft from the `CKComponentLifecycleManager` in the name of minimizing its responsibilities.

Refactor how component tree events are announced.

---

ComponentKit/Core/CKComponentLifecycleManager.h
ComponentKit/Core/CKComponentLifecycleManager.mm
ComponentKit/DataSources/CKCollectionViewDataSource.mm

We actually should always be messaging the *current* scope frame's controllers, not the scope frame from the time the output item was created.
This is confusing, and will be cleaned up during my continuing CLM refactors.

Fix subtle issue with component scope frame messaging

---

ComponentTextKit/CKLabelComponent.mm
ComponentTextKit/CKTextComponent.mm
ComponentTextKit/CKTextComponentView.mm

Enables accessibility by default in CKLabelComponent, and provides an example on how to do more advanced accessibility setups for CKTextComponent.
Should fix https://github.com/facebook/componentkit/issues/127

Enable accessibility in CKLabelComponent by default

---

ComponentKit.podspec
Examples/WildeGuess/Podfile.lock
Podfile.lock

A [recent change](https://github.com/facebook/componentkit/commit/d3e5a427b65b792df085899065667c4c37cfbddb) introduced an umbrella header, `ComponetKit.h`, making wrangling `#import`s much simpler (see the [change in the sample project](https://github.com/facebook/componentkit/commit/d1fd3d8bae281c573c3af5dfdcf15dcfd38b5a3e)). This came after `v0.10`, but it’d be nice to be able to use it.
I’m not sure if this change plus whatever else is on `master` warrants a version `0.11`, but it would be nice.
Thanks! Feel free to disregard if this is jumping the gun. I was just confused by the missing header when trying to integrate ComponentKit into a project of mine while using the example project as a guide.

Request to bump version and tag repo

---

ComponentKit/DataSources/CKCollectionViewDataSource.h
ComponentKit/DataSources/CKCollectionViewDataSource.mm
Examples/WildeGuess/WildeGuess/WildeGuessCollectionViewController.mm

Fix #129, indexPath is not a reliable thing to use for disappearance announcements on deletion (either the index would be out of bounds if the last item is deleted or it will point to an invalid item).
Calling `- (void)announceWillAppearForItemInCell:(UICollectionViewCell *)cell atIndexPath:(NSIndexPath *)indexPath` and `- (void)announceDidDisappearForItemInCell:(UICollectionViewCell *)cell atIndexPath:(NSIndexPath *)indexPath` guarantees the announcement will be dispatched to the component tree associated to the cell. 
It is however non opinionated in the sense that it won't do deduplication of events, or check for imbalanced calls. 
For instance while reloading a cell on screen, the collection view first send appearance events for the newly created cell and then send disappearance …

[CDS] Fix appearance tracking

---

ComponentKit/Utilities/CKArrayControllerChangeset.mm
ComponentKitTests/CKArrayControllerChangesetTests.mm
Examples/WildeGuess/Podfile.lock

Updates and insertions are not applied towards the same index space. They could very well affect the same indexPath in their respective index spaces and the changeset would still be valid.

[CDS] Remove unecessary restrictions on the changesets

---

ComponentKit/DataSources/Common/CKComponentDataSource.mm

Updates the context of all the items before the reload, currently the old context is used for the reload.

Use new context in updateContextAndEnqueueReload

---

ComponentKit/Utilities/CKArrayControllerChangeset.h
ComponentKit/Utilities/CKArrayControllerChangeset.mm
ComponentKitTests/CKArrayControllerChangesetTests.mm

Exposes objc datastructures corresponding to each changeset operations, it will be used to convert changesets to the right format for the transactional datasource.
The other option was to leverage the existing enumeration API but this would have been wasteful. The enumeration vends NSIndexSet and NSArrays (so that we can directly do `insertObjects:AtIndexes:`) that are already the product of a conversion from a cpp datastructure that we would then have had to convert back to NSDictionaries.

[CDS] Add convenience getters to the arrayControllerChangeset

---

ComponentKit/DataSources/Common/CKComponentDataSource.mm
ComponentKit/DataSources/Common/CKComponentDataSourceInputItem.h
ComponentKit/DataSources/Common/CKComponentDataSourceInputItem.mm
ComponentKitTests/CKComponentDataSourceTests.mm

Not needed and was adding some churn on the reload APIs for no reasons.
Also added unit tests for `enqueueReload`, and `updateContextAndEnqueueReload`

Remove context form the input item

---

ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceState.m

If we're going to use the UIKit extensions to NSIndexPath, we have to import UIKit.

Add missing header

---

ComponentKit/Core/CKComponentLifecycleManager.mm

If someone asks for a CLM's layout before it has even had an update prepared, substitute a fake scope root.

Fix hosting view

---

ComponentKit/Core/Scope/CKComponentScopeHandle.mm

When I refactored scope frames, I failed to mark the listener as weak. The result is that every component is leaked forever. Oops.

Fix memory leak in scope handle

---

ComponentKit/Utilities/CKArrayControllerChangeset.h
ComponentKit/Utilities/CKArrayControllerChangeset.mm
ComponentKitTests/CKArrayControllerChangesetTests.mm

Will actually expose the C++ objects and make the conversion in objc structures external for the transactional DS.
Also, given the current work on moves where we eventually get rid of enumeration and the fact that the session getters are actually used internally it makes sense to keep them C++ to avoid the perf penalty of conversion.

"[CDS] Remove convenience objc getters for now"

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit.xcodeproj/xcshareddata/xcschemes/ComponentKit.xcscheme
ComponentKit/Components/CKButtonComponent.mm
ComponentKit/Utilities/CKComponentAction.h
ComponentKit/Utilities/CKComponentAction.mm
ComponentKit/Utilities/CKComponentGestureActions.h
ComponentKit/Utilities/CKComponentGestureActions.mm
ComponentKitApplicationTests/CKComponentActionAttributeTests.mm
ComponentKitTestHelpers/CKTestActionComponent.h
ComponentKitTestHelpers/CKTestActionComponent.mm
ComponentKitTests/CKComponentActionTests.mm
ComponentKitTests/CKComponentGestureActionsTests.mm

This should minimize the places we need to do conditional attributes.
http://componentkit.org/docs/avoid-push-back.html

Allow null action to be passed to `CKComponentActionAttribute`

---

ComponentKit/Utilities/CKArrayControllerChangeset.h
ComponentKit/Utilities/CKArrayControllerChangeset.mm
ComponentKit/Utilities/CKSectionedArrayController.mm

This is a first step in removing enumeration API motivated by incoming moves support in the changeset.
Exposing moves though enumeration would be a bit cumbersome (since we have always assumed each change needs only one indexPath so far) and several callsites assume changes are enumerated in a specific order, which is not really enforced anywhere (and not documented in all places either).
This PR does not remove the enumeration itself yet, since I need to sync this internally a remove all usages there first.

[CDS] remove usage of CKArrayControllerInputItems enumeration

---

ComponentKit/Utilities/CKArrayControllerChangeset.h
ComponentKit/Utilities/CKArrayControllerChangeset.mm
ComponentKit/Utilities/CKSectionedArrayController.mm

After chatting more with @benlodotcom and considering this is a pretty important part of the datasource, I have decided to go with the safest way possible for exposing input items on CKArrayControllerInputItems.
Using a separate enumeration for each operation at once is safer,
since we won't forget update any processing of input items once we add moves.
Also it explicitly shows what kind of items are there to handle, so it's harder to forgot anything when adding a new consumer.

[CDS] safer access to CKArrayControllerInputItems

---

ComponentKit/DataSources/Common/CKComponentDataSource.mm
ComponentKit/Utilities/CKArrayControllerChangeset.h
ComponentKit/Utilities/CKArrayControllerChangeset.mm
ComponentKitTests/CKArrayControllerChangesetTests.mm

Another step closer to adding moves.

[CDS] remove the old item enumeration API from CKArrayControllerChangeset

---

ComponentKit/Debug/CKComponentHierarchyDebugHelper.mm

While printing the layout tree, it is possible that the layout has not even been generated, in which case `layout.children` will be `nil`. Dereferencing it without checking can cause a crash.

[debug] Explicitly check whether there are any children in layout

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/Utilities/CKComponentDelegateAttribute.h
ComponentKit/Utilities/CKComponentDelegateAttribute.mm
ComponentKitTests/CKComponentDelegateAttributeTests.mm

Purpose:
Avoid always needing to have a controller just because you need events from a view. This goes along with the `CKComponentActionAttribute` where you can get events from `UIControl`s sent up to your component or controller subclass.
I could see this being used to allow editing of UITextFields with some work  #222); the obvious uses are scroll views for gestures, etc. that I take advantage of with the combiners example.
Test plan:
I've tried to write some basic unit tests, but I'm interested in hearing what cases are interesting / things that I've missed.
Limitations:
- only allows one delegate to be set per view (can't think of a situation where this is an issue)
- uses associated objects

Add a view attribute to send a delegate protocol to components

---

ComponentKit/Utilities/CKComponentDelegateAttribute.h
ComponentKit/Utilities/CKComponentDelegateAttribute.mm
ComponentKit/Utilities/CKComponentDelegateForwarder.h
ComponentKit/Utilities/CKComponentDelegateForwarder.mm
ComponentKit/Utilities/CKComponentGestureActions.h
ComponentKit/Utilities/CKComponentGestureActions.mm
ComponentKitTests/CKComponentGestureActionsTests.mm

This is the new API:
CKComponentGestureAttribute([UIPanGestureRecognizer class], nullptr, @selector(test:), {@selector(gestureRecognizerShouldBegin:)});
Then you can write in your component's controller (or super-component etc):
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)r
{
...
return YES;
}

Allow proxying gesture recognizers' delegates to the component

---

ComponentKit/DataSources/CKCollectionViewDataSource.mm
ComponentKit/DataSources/Common/CKComponentDataSource.mm
ComponentKit/DataSources/Common/CKComponentPreparationQueue.h
ComponentKit/DataSources/Common/CKComponentPreparationQueue.mm
ComponentKit/Utilities/CKArrayControllerChangeset.h
ComponentKit/Utilities/CKArrayControllerChangeset.mm
ComponentKit/Utilities/CKSectionedArrayController.mm
ComponentKitTests/CKArrayControllerChangesetTests.mm
ComponentKitTests/CKComponentDataSourceTestDelegate.h
ComponentKitTests/CKComponentDataSourceTestDelegate.mm
ComponentKitTests/CKComponentDataSourceTests.mm
ComponentKitTests/CKComponentPreparationQueueAsyncTests.mm
ComponentKitTests/CKComponentPreparationQueueTests.mm
ComponentKitTests/CKSectionedArrayControllerTests.mm

New updates in `CKArrayControllerOutputItems` are no longer specified as `CKArrayControllerOutputChange`, but only as a minimal set of values which specify update command. 
Extends `CKArrayControllerOutputChange` and `CKComponentPreparationItem` to work with two indexPaths.

[CDS] more preparation for moves

---

ComponentKit/Utilities/CKComponentGestureActions.h
ComponentKit/Utilities/CKComponentGestureActions.mm

For #236
Example usage:
````objc++
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer 
shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer
{
std::set<std::pair<SEL, SEL>> allowed{
{@selector(mouseDown:gesture:), @selector(mouseDragged:gesture:)},
{@selector(mouseDown:gesture:), @selector(doubleClick:gesture:)},
{@selector(mouseDown:gesture:), @selector(doubleClickedRedacted:gesture:)},
};
return allowed.find({CKComponentGestureGetAction(gestureRecognizer), CKComponentGestureGetAction(otherGestureRecognizer)}) != allowed.end();
}
````

Provide a way to map back to the actual action selector on a gesture.

---

ComponentKit/LayoutComponents/CKStackLayoutComponent.h
ComponentKit/LayoutComponents/CKStackLayoutComponent.mm

It's a 4-element struct, probably shouldn't be copied.

Pass CKStackLayoutComponentStyle to CKStackLayoutComponent by reference

---

ComponentKit/DataSources/CKCollectionViewDataSource.mm
ComponentKit/DataSources/Common/CKComponentDataSource.h
ComponentKit/DataSources/Common/CKComponentDataSource.mm
ComponentKit/DataSources/Common/CKComponentDataSourceDelegate.h
ComponentKitTests/CKComponentDataSourceTestDelegate.mm

Makes the CKComponentDataSource header less bloated.

[FBCDS] Extract FBComponentDataSourceDelegate in a separate file

---

ComponentKit/Core/CKComponent.mm
ComponentKit/Core/ComponentMountContext.h
ComponentKit/Debug/CKComponentDebugController.mm
ComponentKit/Utilities/CKMountAnimationGuard.h
ComponentKitApplicationTests/CKComponentBoundsAnimationTests.mm
ComponentKitTests/CKComponentViewReuseTests.mm

Otherwise, we fix the issue of unwanted animations in a parent component but the children still animate willy-nilly.

Blocking animations in the parent should block animations in the child

---

ComponentKitTests/CKComponentDataSourceTestDelegate.h

When compiling ComponentKit, a warning is emitted due to a missing
import for CKComponentDataSourceDelegate; see
https://travis-ci.org/facebook/componentkit/builds/68231808#L566.
Add the missing import to fix the warning.

ComponentKitTests: Add missing import

---

ComponentKit/Core/CKComponent.h
ComponentKit/Core/CKComponent.mm
ComponentKit/Core/CKComponentController.h
ComponentKit/Core/CKComponentController.mm
ComponentKit/Core/CKComponentSubclass.h
ComponentKitTests/CKComponentControllerTests.mm

I added the canPerformAction method to the component responder chain (in CKComponent and CKComponentController) so that subclasses of components can choose to implement this method or not. If they do not, the behavior is the same as it was before the methods were added. If subclasses do implement this they can return YES to handle the the event or NO to be skipped in the responder chain and the event will continue to traverse it.
I also added a test to make sure that the correct object is being returned when a component and its controller (the next responder) both implement the method with different conditions.

Adding canPerformAction to the component responder chain

---

ComponentKit/Utilities/CKInternalHelpers.h
ComponentKit/Utilities/CKInternalHelpers.mm
ComponentTextKitApplicationTests/CKTextKitTests.mm

Previously, it would often return 0 since left shifting all previous results by 32-bits deletes a lot of information. Most importantly, the actual text hash!

Fix completely broken hash function

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/StatefulViews/CKStatefulViewComponent.h
ComponentKit/StatefulViews/CKStatefulViewComponent.mm
ComponentKit/StatefulViews/CKStatefulViewComponentController.h
ComponentKit/StatefulViews/CKStatefulViewComponentController.mm
ComponentKit/StatefulViews/CKStatefulViewReusePool.h
ComponentKit/StatefulViews/CKStatefulViewReusePool.mm
ComponentKitTests/StatefulViews/CKStatefulViewComponentControllerTests.mm
ComponentKitTests/StatefulViews/CKStatefulViewReusePoolTests.mm
ComponentKitTests/StatefulViews/CKTestStatefulViewComponent.h
ComponentKitTests/StatefulViews/CKTestStatefulViewComponent.mm

Just a 1:1 import of CKStatefulViewCompontent from the internal repo. This component lets you wrap a view that maintains internal state that you don't control, while still having a stateless API. It's mostly useful for text editing by wrapping UITextView and UITextField. No specific component subclasses are included here, but they can be built as subclasses of CKStatefulViewComponentController.

Open source CKStatefulViewComponent.

---

ComponentKit/Core/CKComponentLifecycleManager.h
ComponentKit/Core/CKComponentLifecycleManager.mm
ComponentKit/HostingView/CKComponentHostingView.mm
ComponentKit/HostingView/CKComponentHostingViewInternal.h
ComponentKitTests/CKComponentHostingViewTests.mm

- No longer uses `CKComponentLifecycleManager`, freeing us from that cruft.
- If only the size of the view changes, but not the model or context, the component is not regenerated. This is more efficient.
- Similarly we cache the computed layout, so if for some reason `layoutSubviews` is called twice with no change to the component or size, we won't expensively re-layout the component.
- Added thread safety asserts.
Next up is to add asynchronous modes for model, state, and context updates.

Refactor ComponentHostingView

---

ComponentKit/HostingView/CKComponentHostingView.h
ComponentKit/HostingView/CKComponentHostingView.mm
ComponentKit/HostingView/CKComponentHostingViewInternal.h
ComponentKitTests/CKComponentHostingViewTests.mm

- Since context is now mutable and is optional in any case, we shouldn't pass it to init.
- Clean up documentation.

Clean up CKComponentHostingView's API

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/Core/CKComponentLifecycleManager.h
ComponentKit/Core/CKComponentLifecycleManager.mm
ComponentKit/Core/CKComponentMemoizer.h
ComponentKit/Core/CKComponentMemoizer.mm
ComponentKit/Core/CKComponentViewAttribute.mm
ComponentKit/Core/CKSizeRange.mm
ComponentKit/Core/Scope/CKComponentScopeFrame.mm
ComponentKit/DataSources/Common/CKComponentDataSourceInputItem.mm
ComponentKit/DataSources/Common/CKComponentDataSourceOutputItem.mm
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceAppliedChanges.mm
ComponentKit/Utilities/CKEqualityHashHelpers.h
ComponentKit/Utilities/CKEqualityHashHelpers.mm
ComponentKit/Utilities/CKInternalHelpers.h
ComponentKit/Utilities/CKInternalHelpers.mm
ComponentKitTests/CKComponentMemoizerTests.mm
ComponentTextKit/TextKit/CKTextKitAttributes.mm
ComponentTextKit/TextKit/CKTextKitRendererCache.mm

This is still pretty rough, but wanted to get it up before I chat with @adamjernst in person tomorrow.
The basic idea is twofold:
1. If you created a component last time with a given set of parameters, when rebuilding the component tree, you can just reuse the previous component. This is easiest done in `+newWithMyModel...`. The only caveat here is that you can't reuse components within a tree, since one component can't be mounted to multiple views.
~~2. If you did a potentially-expensive layout calculation one generation, you don't need to redo it the next one. This ties in directly with component creation, since it doesn't help to reuse components if layout is just going to eat those gains away again.~~ moving to another PR
Rough edges:
- Needs documentation
- Maybe update an example to …

Add opt-in memoization of component creation

---

ComponentKit/Core/CKComponentMemoizer.mm

Fix bug where if you didn't setup the memoizer, but opted into layout memoization, a nil component would be returned in the layout, triggering an assert.
Hit this in a unit test, somewhere.

Fix layout bug where you didn't setup the memoizer

---

.travis.yml
ComponentKit/Core/CKComponentLayout.h

Adds an optional `NSDictionary` field called `extra` to CKComponentLayout that can be used to contain additional information during layout.
This change also pins CocoaPods and Slather to specific versions. Previously Travis CI would install the latest versions which may not always work well together (for some reason or another). Using specific versions should lead to a more deterministic build.

Facilitate the inclusion of additional information during layout.

---

ComponentKit/Core/CKComponentLifecycleManager.mm
ComponentKit/Core/CKComponentLifecycleManagerInternal.h
ComponentKit/Debug/CKComponentHierarchyDebugHelper.mm

* This commit couples view and component hierarchies
* This makes it very easy to match up a view with its component
* A view with an associated component is displayed on the following line with "^->" to indicate the association
* Each level of the hierarchy is further indented by "| "
* The searchUpwards parameter shows the component and view ancestors for a given view
* Tested using example app, WildeGuess
* Checked output both upwards and downwards, for views above, at, and below the CKComponentRootView
* Also works with CKComponentHostingView (which is not used in WildeGuess)
* Much of the code is fragile as it depends getting the root layout from either the CKComponentRootView or CKComponentHostingView

pcomponents now outputs coupled component and view descriptions

---

ComponentKitTests/CKComponentMemoizerTests.mm

This can pose problems when -Werror and -Wshadow flags are enabled.

Address local variable shadowing in the component memoizer tests.

---

_docs/datasource-basics.md

As mentioned in #271, the API shown in the docs (`dataSource:didSelectItemAtIndexPath:`) does not actually exist. I've updated the docs to use the `UICollectionViewDelegate`-API.

fixed UICollectionViewDelegate API usage

---

_docs/datasource-gotchas.md

`objectAtindexPath` is not a method on `CKCollectionViewDataSource`

Fix incorrect method name

---

ComponentKit/DataSources/Common/CKComponentDataSourceAttachController.mm

This needs to be marked static or it will fail to compile in some environments.

Fix obscure build issue with CKComponentDataSourceAttachController

---

ComponentSnapshotTestCase/CKComponentSnapshotTestCase.mm
ComponentSnapshotTestCase/ComponentSnapshotTestCase.podspec
ComponentTextKitApplicationTests/CKTextKitTests.mm
Podfile.lock

Hi all,
Some minor updates to the podpsecs that currently cause pain on `master` (which we're using...). The podfile doesn't limit the version of `FBSnapshotTestCase`, so some minor changes required.

Snapshot test case updates

---

ComponentKit/DataSources/CKCollectionViewTransactionalDataSource.h
ComponentKit/DataSources/CKCollectionViewTransactionalDataSource.mm

Hi all,
I noticed that `CKCollectionViewTransactionalDataSource` lacks an equivalent to `CKCollectionViewDataSource`'s `-modelForItemAtIndexPath:` method. Seems like an accidental omission to me, since the implementation is trivial, and it would certainly be a necessity for us to migrate to the new class. So... here it is here.

Add -modelForItemAtIndexPath to CKCollectionViewTransactionalDataSource

---

ComponentKit/Debug/CKComponentHierarchyDebugHelper.mm

+ Added the parameter showViews to `componentHierarchyDescriptionForView:searchUpwards:showViews:`
+ When showViews is YES, views are shown.
+ When showViews is NO, views are not shown.
+ The default behavior when the flag is not set, is to set showViews to YES.
+ The benefit of setting showViews to NO is that views with long descriptions do not clutter up the component hierarchy.

Added flag to pcomponents to toggle the display of views

---

ComponentKit/Debug/CKComponentHierarchyDebugHelper.mm

+ Fixed a bug with pcomponents where if showViews was NO then it wouldn't print anything at all.
+ It now traverses down the view hierarchy without printing out the views and then continues with normal behavior once it hits CKComponentRootView.
+ Also updated some of the indentation on computeDescription and recursiveDescriptionForLayout
+ Replaced all instances of {0, 0} with CGSizeZero/CGPointZero

Fixed a bug with pcomponents

---

ComponentTextKit/TextKit/CKTextKitTailTruncater.mm
ComponentTextKitApplicationTests/CKTextKitTruncationTests.mm

Hi guys,
Have seen this kind of crash in our logs:
```
2015-08-07 16:04:57.985 <REDACTED>[19467:2606941] !!! _NSLayoutTreeLineFragmentRectForGlyphAtIndex invalid glyph index 18446744073709551615
2015-08-07 16:04:57.987 <REDACTED>[19467:2606941] !!! _NSLayoutTreeLineFragmentUsedRectForGlyphAtIndex invalid glyph index 18446744073709551615
2015-08-07 16:04:58.009 <REDACTED>[19467:2606941] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSConcreteTextStorage attributesAtIndex:effectiveRange:]: Range or index out of bounds'
...
* frame #10: 0x0000000191cf805c UIFoundation`-[NSConcreteTextStorage attributesAtIndex:effectiveRange:] + 148
frame #11: 0x0000000100800484 <REDACTED>`-[CKTextKitTailTruncater _calculateCharacterIndexBeforeTruncationMessage:textStorage:te …
```

Fix potential crash in CKTextKitTailTruncater with extremely constrained bounds

---

ComponentTextKit/TextKit/CKTextKitRenderer+Positioning.mm

This assert is inside a block, so we should use the `CKCFailAssert` instead of plain `CKFailAssert`.

Fix assert inside block

---

ComponentKit/Core/CKComponentBoundsAnimation.h
ComponentKit/Core/CKComponentBoundsAnimation.mm

Add UIViewAnimationOptions options field to the CKComponentBoundsAnimation struct to enable components to apply specific UIViewAnimationOptions to the animation.

Add animation options to CKComponentBoundsAnimation

---

ComponentSnapshotTestCase/CKComponentSnapshotTestCase.h
ComponentSnapshotTestCase/ComponentSnapshotTestCase.podspec
Podfile.lock

Use new method of looking up reference images introduced in version 2.0.4. This will cause images to be looked up in bundle if FB_REFERENCE_IMAGE_DIR is empty string.

Use new method of reference image lookup in FBSnapshotTestCase

---

ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceChangesetModification.mm
ComponentKitTests/TransactionalDataSource/CKTransactionalComponentDataSourceChangesetModificationTests.mm

We have to remove the row at the index path the move originates at, not the index path it ends at.

[TDS][fix] remove the correct indexPath for moves

---

ComponentSnapshotTestCase/CKComponentSnapshotTestCase.h
ComponentSnapshotTestCase/CKComponentSnapshotTestCase.mm

Hi all,
Just a simple one here - `FBSnapshotTestCase` has had the `tolerance` feature available since baae047998f6c3f5ace0d38daad5653bc3aee385. However, it's not easily accessibly from `CKComponentSnapshotTestCase`. We certainly do a lot of re-recording of reference images for things like major OS updates (we had loads for 8 -> 9) where inconsequential minor pixel changes happen, so it would be great to make use of this.
Seems fine to just have it as a property of the test case since it would seem to me that one would set this to a value that's a "policy" of sorts across the board.
Anyway, let me know!

Make FBSnapshotTestCase tolerance property accessible

---

.gitignore
ComponentKit.xcodeproj/project.pbxproj
ComponentKit.xcodeproj/xcshareddata/xcschemes/ComponentKit.xcscheme
ComponentKitApplicationTests/ComponentKitApplicationTests-Info.plist
ComponentKitApplicationTestsHost/ComponentKitApplicationTestsHost-Info.plist
ComponentKitApplicationTestsHost/ComponentKitApplicationTestsHostAppDelegate.m
ComponentKitTests/ComponentKitTests-Info.plist
ComponentTextKitApplicationTests/ComponentTextKitApplicationTests-Info.plist

Hi all,
Just a few unglamourous fixes necessitated by Xcode7:
1. Key window with `nil` `rootViewController` now throws an exception, so threw a vanilla `UIViewController` in there.
2. Running tests now gives me `ObjectiveC.gcno` and `ObjectiveC.gcda` files in the project directory, so added those to `.gitignore`. This seems like a fine solution? Although I'm not sure why the change.
3. Applied Xcode's usual "recommended project updates" rigamarole. 
One that I haven't been able to fix, though, and which could be added here is `-[CALayer ck_isAsyncTransactionContainer]`: the method is missing when running with Xcode7 (irrespective of iOS 8 or 9), so *every* test in `ComponentTextKitApplicationTests` fails. I would fix it, but I can't for the life of me find out where this method is added …

Some Xcode 7-oriented project fixes

---

ComponentTextKit/Utility/CKAsyncTransactionContainer.m

As discussed in https://github.com/facebook/componentkit/pull/392, using `CALayer` as a key-value store no longer works under iOS 9. So simply provided explicit associated object storage for this property.

Use associated object storage for ck_asyncTransactionContainer

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/DataSources/CKCollectionViewDataSource.h
ComponentKit/DataSources/CKCollectionViewTransactionalDataSource.h
ComponentKit/DataSources/CKCollectionViewTransactionalDataSource.mm
ComponentKit/DataSources/CKSupplementaryViewDataSource.h
ComponentKitTests/TransactionalDataSource/CKCollectionViewTransactionalDataSourceTests.mm

Resolves https://github.com/facebook/componentkit/issues/394.
Ok, we found that problem! `CKCollectionViewTransactionalDataSource` doesn't forward supplementary view methods à la `CKCollectionViewDataSource`. Since we use section headers implemented previously with `CKCollectionViewDataSource` we return non-zero sizes for the expected supplementary views. `CKCollectionViewTransactionalDataSource` doesn't implement the supplementary view method and hence the collectionView starts playing with `nil` views.
Problem solved and QED. Trivial to implement. Please let me know any suggested adjustments.

Add CKSupplementaryViewDataSource support to transactional data source

---

ComponentKit/DataSources/CKCollectionViewDataSource.mm

Prior iOS9 UIKit does not use ARC, we have to clear weak ref manually.

Fixed dangling datasource pointer

---

ComponentKit/Debug/ComponentKit+QuickLook.mm

Hi all,
Just a quick simple debugging aid for Xcode users here. Very trivial addition, but looks potentially very helpful. Up until this point I've been using Chisel for this myself, but direct Quicklook access via LLDB seems much more user friendly:
Let me know what you think.
Thanks!

debugQuickLookObject categories

---

ComponentKit/DataSources/Common/CKComponentPreparationQueue.mm
ComponentKit/HostingView/CKComponentHostingView.mm
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSource.mm
ComponentKit/Utilities/CKWatchdogTimer.h
ComponentKit/Utilities/CKWatchdogTimer.mm

The process of building a component may deadlock. Add a class that will detect this case and fire a configurable C function pointer when it occurs.

Add configurable watchdog timer

---

ComponentKitTests/CKComponentViewAttributeTests.mm

Increased the coverage of CKComponentViewAttribute setter methods by adding:
- Test all supported types in `performSetter()`
- Direct testing of setting an attribute on the layer, of a component's view, with `CKComponentViewAttribute::LayerAttribute()`.

Expand CKComponentViewAttribute coverage

---

ComponentTextKit/TextKit/CKTextKitRenderer+Positioning.mm
ComponentTextKitApplicationTests/CKTextKitTests.mm

This was a needless assert. Remove it and just clamp the range to the string range. Add a test to confirm this works.
Resolves https://github.com/facebook/componentkit/issues/428

[text] Fix crash when highlighted range exceeds truncation range

---

ComponentTextKit/TextKit/CKTextKitRenderer+TextChecking.mm

Previously we were just taking the *first* glyph instead of the closest. This resulted in a weird edge case where if there was a link directly above your link, it was nearly impossibly to hit any glyphs in the link you were pressing on.  This diff just computes the distance of every candidate glyph in the enumeration, and then takes the minimum centroidal distance.
Result? When I put lots of links near eachother in a text component, it correctly highlights the right links every time...
Should resolve https://github.com/facebook/componentkit/issues/303 .

[text] Use the closest glyph to determine hit token

---

ComponentKit/Core/CKComponentViewAttribute.h
ComponentKitTests/CKComponentViewAttributeTests.mm

Instead of forcing people to manually box values for setters, we can use c++ to deduce the right way to box it for them. Still backwards compatible with manual boxing.
Shouldn't cause additional overhead, but we should test just in case.

Allow primitive values in view attribute maps

---

ComponentKit/DataSources/CKCollectionViewDataSource.mm
ComponentKit/DataSources/Common/CKComponentDataSource.mm
ComponentKit/DataSources/Common/CKComponentPreparationQueue.mm
ComponentKit/Utilities/CKArrayControllerChangeset.h
ComponentKit/Utilities/CKArrayControllerChangeset.mm
ComponentKit/Utilities/CKSectionedArrayController.mm
ComponentKitTests/CKArrayControllerChangesetTests.mm
ComponentKitTests/CKComponentDataSourceTestDelegate.mm
ComponentKitTests/CKSectionedArrayControllerTests.mm

Both `UITableView` and `UICollectionView` support moving cells and sections. I want to support moving cells and sections within ComponentKit. This feature is not relevant for the news feed use case as much, but is for other user interfaces.
Moves operate like both an insertion and a deletion:
- You cannot delete an item at index path 1 and move an item from index path 1 at the same time
- You cannot insert an item at index path 2 and move an item to index path 2 at the same time
But a move is not like an insertion/deletion because it exhibits a different animation and preserves the cell that is being moved (if it's on screen).
I wanted to put this here as a working draft to see if there are any elements/approaches that should be changed. Right now it is missing the following:
- Throwing …

Add move support to CKArrayController

---

ComponentKit/Components/CKNetworkImageComponent.mm

This is the 2nd attempt to fix this. This one is respecting cropRect and is only doing the necessary steps in setSpecifier based on what fields changed in the specifier.

Fix flash in CKNetworkImageComponent when defaultImage is different.

---

ComponentTextKit/CKLabelComponent.h
ComponentTextKit/CKLabelComponent.mm
ComponentTextKit/CKTextComponent.h
ComponentTextKit/CKTextComponent.mm
ComponentTextKitApplicationTests/CKLabelComponentTests.mm
ComponentTextKitApplicationTests/CKTextComponentTests.mm
Examples/WildeGuess/WildeGuess/Components/FrostedQuoteComponent.mm
Examples/WildeGuess/WildeGuess/Components/MonochromeQuoteComponent.mm
Examples/WildeGuess/WildeGuess/Components/SombreQuoteComponent.mm
Examples/WildeGuess/WildeGuess/Components/SuccessIndicatorComponent.mm
Examples/WildeGuess/WildeGuess/Components/WarmQuoteComponent.mm

In response to #444, I added new constructors instead of replacing the old ones for backward compatibility. Please take a look @ocrickard

Add size attribute to CKLabelComponent and CKTextComponent constructors

---

ComponentKit/HostingView/CKComponentRootView.m
ComponentKit/HostingView/CKComponentRootViewInternal.h
ComponentKit/LayoutComponents/CKCenterLayoutComponent.h
ComponentKitTests/CKComponentContextTests.mm
ComponentKitTests/Scope/CKComponentScopeTests.mm
ComponentKitTests/Scope/CKStateScopeComponentBuilderTests.mm

Thanks to @ianolito for the contributions to CKComponentRootView and @mdsilber for the contribution to CKCenterLayoutComponent.

Pass the default view returned by CKComponentRootView's hit test implementation to the hit test hook

---

ComponentKit/Utilities/CKArrayControllerChangeset.h
ComponentKit/Utilities/CKArrayControllerChangeset.mm

The `mapIndex` method is public and may still be used. Let's add it back for now.
I'm not quite familiar with the reasoning behind removing it in the first place. We should make sure that it isn't incompatible with the changes introduced in #414.

Replace the mapIndex method on CKArrayControllerSections

---

ComponentKit/Core/CKComponentAnimation.h
ComponentKit/Core/CKComponentAnimation.mm

Add convenience `CKComponentAnimation` initialization method for animating the `CALayer` at a specific key path.
Right now, animations are performed on the component's view's layer. Often I use a `UIView` subclass when design requires a view with multiple layers. Animating these layers requires dropping down to a custom `CKComponentAnimationHooks`. This PR abstracts `hooksForCAAnimation` for flexibility. 
Example: A view's layer has a CAShapeLayer as the mask. The path of the mask needs be animated on initial mount. We can now achieve this with:
```Objective-C++
- (std::vector<CKComponentAnimation>)animationsOnInitialMount
{
return { {self, [CABasicAnimation animationWithKeypath:@"path"], "layer.mask"} };
}
```

Add CKComponentAnimation on layer at key path

---

_docs/20-datasource-dive-deeper.md

It seem like the CKArrayControllerOutputChange API has changed. The [UITableView's demo](http://componentkit.org/docs/datasource-dive-deeper.html) doesn't compile.

Fixing UITableview's demo code

---

ComponentTextKit/CKLabelComponent.h

Adds the size parameter description to to inline documentation of CKLabelComponent

Added inline doc size parameter, closes #471

---

ComponentKit/DataSources/Common/CKComponentDataSourceAttachController.mm
ComponentKit/DataSources/Common/CKComponentDataSourceAttachControllerInternal.h
ComponentKit/Debug/CKComponentHierarchyDebugHelper.mm

`pcomponents` relies on being able to find the layout of the component
hierarchy from the root view. The mapping existed for the legacy data
source but doesn't exist for the transactional one.
This adds a mapping from root view to layout in the transactional data
source that can be accessed using an internal header. It also fixes up
`pcomponents` so that `pcomponents` uses this mapping.

Fix pcomponents for CKTransactionalComponentDataSource

---

ComponentKit/Core/Scope/CKComponentScopeHandle.mm

The prompt was saying 'Use CKComponentScope(self)' but put that in code will get you a compile error. The most common way to add scope is 'CKComponentScope scope(self)'

update CKComponentScope prompt to the correct format

---

ComponentKit/HostingView/CKComponentHostingView.mm
ComponentKitTests/CKComponentHostingViewTests.mm

Allow CKComponentHostingView to rerender with empty bounds

---

ComponentKit/Core/Scope/CKComponentScope.h
ComponentKit/Core/Scope/CKComponentScope.mm

This is useful when you want to pass a state updater off to some element that is a sub-element of your component (and thus you can't wait until the component is created to pass it off).

Expose a way to get state updater from CKComponentScope

---

ComponentKit/Core/Scope/CKComponentScope.h
ComponentKit/Core/Scope/CKComponentScope.mm

This outright crashed because it captured a member variable on an instance that will be destroyed when the stack unwinds.

Docs and fixes for CKComponentScope stateUpdater

---

.travis.yml
build.sh

`xctool` has been reported to run into trouble with Xcode 7.3. For some context read through some of the more recent comments in https://github.com/travis-ci/travis-ci/issues/3986.
Let's just stick with `xcodebuild` instead.

Use xcodebuild instead of xctool for CI

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/ComponentKit.xcconfig
ComponentKit/Core/CKComponentMemoizer.h
ComponentKit/DataSources/CKCollectionViewTransactionalDataSource.h
ComponentKit/DataSources/Common/CKComponentAnnouncerHelper.h
ComponentKit/DataSources/Common/CKComponentDataSourceAttachController.h
ComponentKit/Utilities/CKArrayControllerChangeset.h
ComponentKit/Utilities/CKMutex.h
ComponentTextKit/TextKit/CKTextKitRenderer.mm
ComponentTextKit/TextKit/CKTextKitRendererCache.h

I went through and pruned the `Public` headers for only things that are imported via the umbrella header, made anything that might need to be accessed `Private`, and left the rest of the headers as `Project`.
Also, I found some warnings with `-Wall` and `-Wextra` and turned on those flags for `Debug` builds.

Build improvements

---

ComponentTextKit/TextKit/CKTextKitRenderer.mm
ComponentTextKitApplicationTests/CKTextKitTruncationTests.mm

This is an attempt to address the issue that @conradev illustrated with #553.
The issue is that our loop is looking at `[layoutManager numberOfGlyphs]` which counts all glyphs and not just what is visible. I am adding a check to ensure that `lineFragmentRectForGlyphAtIndex` returns non empty rect before increasing the count. This was modeled as the documentation [describes](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/TextLayout/Tasks/CountLines.html) and it worked as expected when `maximumNumberOfLines` was not set.
Any suggestions would be appreciated.

Fix maximumNumberOfLines on CKTextKitRenderer

---

ComponentKit/StatefulViews/CKStatefulViewReusePool.mm
ComponentKitTests/StatefulViews/CKStatefulViewReusePoolTests.mm

Credit to @RomanoffAlex for finding this and proposing a fix. His description of the problem follows:
If we have preferredSuperviewMap like the following:
```
superview: [view].
```
and allViews:
```
[view].
```
Imagine that we call `viewWithPreferredSuperview(UIView *preferredSuperview)` with some `preferredSuperview` that is not in the map and a corresponding stateful view (which was picked to be recycled) doesn't have a superview.
In this case we will remove the `preferredSuperview` from `allViews` but keep it in `preferredSuperviewMap` which is really bad because if we later call `viewWithPreferredSuperview` with a superview that is a key in the map, we will reuse the view that already is used by some component that means we are stealing a stateful view from another superview that is …

Fix stateful view reuse pool bug with superview changes

---

ComponentKit/Utilities/CKOptimisticViewMutations.h
ComponentKit/Utilities/CKOptimisticViewMutations.mm
ComponentKitTests/CKOptimisticViewMutationsTests.mm

Sometimes an optimistic view mutation may want to affect the view in a way that cannot be expressed as a keypath; for example, a UIButton's title.
This pull request adds a new API for expressing these optimistic view mutations and introduces tests for it.

More advanced API for optimistic view mutations

---

ComponentKit/Core/CKComponentLayout.mm

This function is on pretty hot path and allocating a block is
unnecessary for such a simple and static a function.

Change CKOffMainThreadDeleter to use function pointers instead of blocks

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit.xcodeproj/xcshareddata/xcschemes/ComponentKitAppleTV.xcscheme
ComponentKit/Components/CKButtonComponent.mm
build.sh

Things Just Work *except* for `CKButtonComponent` uses `sizeWithFont` which is marked as `__TVOS_PROHIBITED`. It uses sizeWithFont to calculate the intrinsic size. This proposes `#if TARGET_OS_TV`, intrinsic size = INFINITY, INFINITY. (I minimally tested this by creating a CKButtonComponent in a vertical stack and it seemed to act as expected. Note the button isn't focusable as-is, but I haven't thought much about that but I think that should be addressed separately (if needs addressing)).
The rest of the changes are to attempt to make sure things stay Just Working (at least building) by adding tvOS targets (using Duplicate option on the existing ones - better way?) and building them with `build.sh ci`.
I also tested Carthage support with a brand new tvOS project and a Cartfile of `github …

Support for using ComponentKit with tvOS

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/Core/CKComponent.mm
ComponentKit/Core/CKComponentInternal.h
ComponentKit/Core/CKComponentLayout.h
ComponentKit/Core/CKComponentLayout.mm
ComponentKit/Core/CKComponentLifecycleManager.mm
ComponentKit/Core/CKComponentMemoizer.h
ComponentKit/Core/CKComponentSubclass.h
ComponentKit/Core/Scope/CKComponentScope.mm
ComponentKit/Core/Scope/CKComponentScopeFrame.mm
ComponentKit/Core/Scope/CKComponentScopeHandle.h
ComponentKit/Core/Scope/CKComponentScopeHandle.mm
ComponentKit/Core/Scope/CKDetectComponentScopeCollisions.h
ComponentKit/Core/Scope/CKDetectComponentScopeCollisions.mm
ComponentKit/HostingView/CKComponentHostingView.mm
ComponentKit/LayoutComponents/CKCenterLayoutComponent.mm
ComponentKit/LayoutComponents/CKOverlayLayoutComponent.mm
ComponentKit/LayoutComponents/CKRatioLayoutComponent.mm
ComponentKit/LayoutComponents/CKStackUnpositionedLayout.mm
ComponentKit/LayoutComponents/CKStaticLayoutComponent.mm
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceChangesetModification.mm
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceReloadModification.mm
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceUpdateConfigurationModification.mm
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceUpdateStateModification.mm
ComponentKitTests/Scope/CKComponentScopeTests.mm

Component scope collision detection originally took place at component scope creation, during component preparation. This behavior wasn't entirely correct because components created during component preparation may not actually make their way to component layout.
Instead ComponentKit should attempt to detect component scope collisions during component layout. Not only is this more correct behavior but it also allows us to provide (not yet implemented) a more actionable error message.
To support this new behavior a couple of other notable changes were required:
1. Propagate the global identifiers of component scope handles with the same component class and identifier pair
2. Add a new `CKComputeTopLevelComponentLayout` function responsible for computing component layouts for top-level …

Move component scope collision detection to component layout

---

ComponentKit/Accessibility/CKComponentAccessibility.h
ComponentKit/Accessibility/CKComponentAccessibility.mm
ComponentKit/Components/CKButtonComponent.h
ComponentKit/Components/CKButtonComponent.mm
ComponentKitTests/CKComponentAccessibilityTests.mm
ComponentTextKit/CKTextComponent.h
ComponentTextKit/CKTextComponent.mm

We shouldn't pass in accessibilityIdentifier as part of accessibility context as it's an automation feature, not an accessibility one. See issue #590 for more details.
This diff removes the use of the identifier, forcing people to pass it in correctly and consistently if they want to use it (e.g. `{@selector(setAccessibilityIdentifier:), @"accessibilityId"}` in attributes).
Test plan: ran all the tests, made sure that passing accessibilityIdentifier correctly works as expected

Removed accessibilityIdentifier from context (fixes issue #590)

---

ComponentKit/Base/CKAssert.h
ComponentKit/Core/Scope/CKDetectComponentScopeCollisions.mm

To test I added `CKCFailAssert` immediate after `#if CK_ASSERTIONS_ENABLED` in `CKDetectComponentScopeCollisions`. I then ran the example app with both `Debug` and `Release` build configurations and verified that the former triggered the assertion, the latter did not.

Introduce CK_ASSERTIONS_ENABLED

---

ComponentKit/Core/Scope/CKThreadLocalComponentScope.h
ComponentKit/Core/Scope/CKThreadLocalComponentScope.mm
ComponentKitTests/Scope/CKComponentScopeTests.mm

For some threading experiments we're doing, we need to able to temporarily override the current thread local component scope. I encapsulated this in a C++ class so cleanup is guaranteed to happen.

Add ability to temporarily override CKThreadLocalComponentScope

---

ComponentTextKit/TextKit/CKTextKitTailTruncater.mm

Lack of range checks were causing us to pass invalid values into -[NSString rangeOfCharacterFromSet:options:range:] leading to an exception being thrown.

Add missing range checks

---

ComponentKit/Core/Scope/CKComponentScopeFrame.mm
ComponentKitTests/Scope/CKComponentScopeTests.mm

See comment in `CKComponentScopeFrame` for details.

Share the initial component scope tree across all colliding component scopes

---

ComponentKit/Core/CKComponentLayout.mm

When you set an CKComponentLayout ivar for the first time, it’s already
initialized with the default initializer. Because of this, the deleter
is triggered with an empty array. The innocuous setting of an ivar
therefore triggers a semi-expensive dispatch. It’s a lot cheaper to
simply delete this object on the main thread.

Don't dispatch the deleter off the main thread if the layout vector is empty

---

Cartfile.resolved
build.sh

As noted in https://github.com/facebook/componentkit/pull/373, `build.sh` doesn't appear to be fully set up to build using Carthage. Hot-wiring here :). Looking good now.

Install and update Carthage in build script

---

ComponentKit/Core/CKComponent.mm

_mountInfo is a mutable main-thread affined portion of the component. We don't lock on access, yet internally have some crashes due to what appears may be multithreaded access to the mount info. If any of this is ever accessed off-main, then you're likely to corrupt the heap, since you can't control when you are unmounted, and that pointer is unset on the main thread. There is no atomic barrier around the unique_ptr reset().

Add main thread assertions for mount info

---

ComponentKit/Core/CKComponentController.h
ComponentKit/Core/CKComponentController.mm
ComponentKit/Core/Scope/CKComponentScope.mm
ComponentKit/Core/Scope/CKComponentScopeFrame.mm
ComponentKit/Core/Scope/CKComponentScopeHandle.h
ComponentKit/Core/Scope/CKComponentScopeHandle.mm
ComponentKitTests/CKComponentControllerLifecycleMethodTests.mm
ComponentKitTests/CKComponentControllerTests.mm

As discussed in https://github.com/facebook/componentkit/issues/504
CKComponentController component can be nil until first mount. This diff
changes the initializer of CKComponentController to instead take in a
component on init, and changes the initialization order for controllers
inside scope handles.

[ck] Fix controller.component = nil before mount

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/DataSources/CKCollectionViewTransactionalDataSource.mm
ComponentKitTests/TransactionalDataSource/CKTransactionalComponentDataSourceIntegrationTests.mm

Resolves https://github.com/facebook/componentkit/issues/342
As noted in the issue, I encountered the same remounting issue with the new data source as encountered in the original (https://github.com/facebook/componentkit/pull/256). The first part of the problem was to use the same technique of grabbing any existing cell for the index path and reusing it. Then an additional problem *seemed* to be that changes were applied to the collection view before updating the local state in `CKCollectionViewTransactionalDataSource`. Simply moving the `applyChangesToCollectionView()` call until after that fixed this.
So... this appears at quick inspection to fix the issue although I'm certainly not 100% confident about the ramifications. I also thought about migrating the example app to the new data …

Remount transactional data source

---

build.sh

`xcpretty` hides potentially helpful output when there are build failures. Due to recent CI flakiness I think it makes sense to drop `xcpretty` support to get more verbose output.

Remove xcpretty from the CI build script

---

ComponentKit/Core/Scope/CKComponentScopeHandle.mm
ComponentKitTests/CKComponentControllerTests.mm

Fixes https://github.com/facebook/componentkit/issues/640 and is more
defensive with the resolution assertion.

Add assertion & avoid useless controller creation

---

ComponentKit/Core/Scope/CKComponentScopeFrame.mm
ComponentKit/Core/Scope/CKComponentScopeHandle.h
ComponentKit/Core/Scope/CKComponentScopeHandle.mm
ComponentKitTests/CKComponentControllerTests.mm

To help address nil components in component controllers we changed the lifecycle of component controllers. Unfortunately this introduced a regression in "announceable" event registration. More concretely folks are not receiving the following appearance events after a state update has been applied:
1. `-[CKComponentController componentTreeWillAppear]`
2. `-[CKComponentController componentTreeDidDisappear]`
To fix this problem `CKComponentScopeHandle` must make sure to register component controllers for announceable events with the new `CKComponentScopeRoot`. This should only happen when an existing `CKComponentScopeHandle` is updated with the relevant state updates.
Prior to this change the only time a component controller would register for announceable events is at the point in time the …

Register for announceable events after state updates

---

.travis.yml
Cartfile.private
Cartfile.resolved
ComponentKit.xcodeproj/project.pbxproj
ComponentKit.xcodeproj/xcshareddata/xcschemes/ComponentKit.xcscheme
ComponentKit.xcodeproj/xcshareddata/xcschemes/ComponentKitAppleTV.xcscheme
build.sh

Now that `ios-snapshot-test-case` 2.1.3 is out we can move ComponentKit Travis CI builds to Xcode 8, iOS 10, and tvOS 10.

Xcode 8 travis ci builds

---

ComponentKit/Core/ComponentUtilities.h

These should be using the std::begin/std::end iterators explicitly.
Previous this worked with std::collections due to argument dependent lookup, but by being explicit we can allow any collection class that is compatible with std::iterators to be passed to the iterable map.

Allow CK::map to work with any iterable

---

ComponentKit/DataSources/CKComponentBoundsAnimation+UICollectionView.mm

It's possible that the collection view driving bounds animations may not be visible. In these situations the mapping of index paths to original layout attributes will be empty. If ComponentKit cannot determine the largest animating visible element it will crash when trying to lookup the layout attributes.
To avoid the crash bounds animations should not be applied if the visible rect is empty.

Do not attempt to apply bounds animations if the collection view is not visible

---

ComponentKit.xcodeproj/project.pbxproj

Resolve linker warnings by cleaning up framework search paths and specifying a consistent iOS deployment target.

Fix linker warnings

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceChangesetVerification.h
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceChangesetVerification.mm
ComponentKit/Utilities/CKArrayControllerChangesetVerification.h
ComponentKit/Utilities/CKBadChangesetOperationType.h
ComponentKitTests/TransactionalDataSource/CKTransactionalComponentDataSourceChangesetVerificationTests.mm

A `CKTransactionalComponentDataSourceChangeset` port of #599.

Add support for CKTransactionalComponentDataSourceChangeset verification

---

ComponentKit/DataSources/CKCollectionViewTransactionalDataSource.h
ComponentKit/DataSources/CKCollectionViewTransactionalDataSource.mm
Examples/WildeGuess/WildeGuess.xcodeproj/project.pbxproj
Examples/WildeGuess/WildeGuess/WildeGuessCollectionViewController.mm

Per #558 one of the first steps in removing `CKComponentDataSource` is migrating the WildeGuess example app to the `CKCollectionViewTransactionalDataSource`.
Test Plan:
Build and run the WildeGuess example app. Ensure quotes are rendered and interaction is supported.

Migrate WildeGuess to CKCollectionViewTransactionalDataSource

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSource.mm
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceChangesetModification.h
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceChangesetModification.mm
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceChangesetVerification.h
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceChangesetVerification.mm
ComponentKit/Utilities/CKArrayControllerChangesetVerification.h
ComponentKit/Utilities/CKArrayControllerChangesetVerification.mm
ComponentKit/Utilities/CKBadChangesetOperationType.h
ComponentKit/Utilities/CKBadChangesetOperationType.mm
ComponentKit/Utilities/CKSectionedArrayController.mm
ComponentKitTests/TransactionalDataSource/CKTransactionalComponentDataSourceChangesetVerificationTests.mm
Examples/WildeGuess/WildeGuess/WildeGuessCollectionViewController.mm

Adds an assertion to `CKTransactionalComponentDataSource` as changesets are applied.
Test Plan:
Trigger bad changesets in WildeGuess and verify assertions are raised.

Verify transactional component data source changesets

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/DataSources/CKCollectionViewTransactionalDataSource.mm
ComponentKitTests/TransactionalDataSource/CKTransactionalComponentDataSourceIntegrationTests.mm

Hi all :),
So had a chance to revisit this (https://github.com/facebook/componentkit/pull/373) and refresh my memory. New version should be cleaner and more sensical.
In particular, found a better way to approach the test: by force-casting `CKTransactionalComponentDataSourceConfiguration` to accept the `XCTestCase` instance itself as the component provider, it's possible to retain the generated components and access the controller directly. Then, can just log the callbacks received and everything becomes straightforward and conventional enough. Not to mention far shorter.
Other comments on their respective lines.
Thanks!

Re-attach existing cells using new state to support animations in reloads

---

ComponentKit.xcodeproj/project.pbxproj

This tests were missing from the tvOS test target.

Include missing tvOS tests

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/Core/CKComponent.mm
ComponentKit/Core/CKComponentBacktraceDescription.h
ComponentKit/Core/CKComponentBacktraceDescription.mm
ComponentKit/Core/Scope/CKDetectComponentScopeCollisions.mm

Annotate `CALayerInvalidGeometry` exceptions raised during mount with the name of the offending component.
Test Plan:
Artificially trigger the exception by inserting a `NAN` when computing the view's center:
```
[v setCenter:effectiveContext.position + CGPoint({size.width * anchorPoint.x, size.height * anchorPoint.y + NAN})];
```
Run the snapshot tests and verify the exception is raised with the updated reason:
```
"CALayerInvalidGeometry", "CKTextComponent raised CALayerInvalidGeometry during mount: CALayer position contains NaN: [50.5 nan]"
(
0   CoreFoundation                      0x00000001054c434b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x0000000104f2521e objc_exception_throw + 48
2   CoreFoundation                      0x000000010552d265 +[NSException …
```

Raise exceptions that include the name of the offending component during mount

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/Components/CKButtonComponent.h
ComponentKit/Components/CKButtonComponent.mm
ComponentKit/Core/Scope/CKComponentScope.h
ComponentKit/Core/Scope/CKComponentScope.mm
ComponentKit/Core/Scope/CKComponentScopeHandle.h
ComponentKit/Core/Scope/CKComponentScopeHandle.mm
ComponentKit/Utilities/CKComponentAction.h
ComponentKit/Utilities/CKComponentAction.mm
ComponentKit/Utilities/CKComponentActionInternal.h
ComponentKit/Utilities/CKComponentGestureActions.h
ComponentKit/Utilities/CKComponentGestureActions.mm
ComponentKit/Utilities/CKComponentGestureActionsInternal.h
ComponentKit/Utilities/CKInternalHelpers.h
ComponentKit/Utilities/CKInternalHelpers.mm
ComponentKitApplicationTests/CKComponentActionAttributeTests.mm
ComponentKitTestHelpers/CKTestActionComponent.h
ComponentKitTestHelpers/CKTestActionComponent.mm
ComponentKitTests/CKComponentActionTests.mm
ComponentKitTests/CKComponentGestureActionsTests.mm

This one is a doozey, and will break some current code written with ComponentKit, though I've tried my best to make the conversion path simple. Please review thoroughly.
This PR is attempting to make the CKComponentAction declaration a little bit clearer. We're providing a few new facilities:
1. CKComponentActions can now take arbitrary target/selector pairs instead of necessarily using the responder chain.
2. CKComponentAction now has a typed variant which allows specification of the arguments to the action method.
3. An execution block can be created from an action which can simply be executed with the arguments defined in the variadic types. This allows simple interop with systems that expect raw blocks as inputs for their actions (like JSC). (I haven't implemented this yet, …

Make actions typesafe through templated type

---

ComponentKit/Utilities/CKComponentAction.h

This already landed internally to fix dylib builds for certain device configurations. I'm unclear on why certain architectures require this explicit destructor.

Fix build for certain device and dylib builds

---

ComponentKit/Utilities/CKComponentAction.h
ComponentKit/Utilities/CKComponentAction.mm
ComponentKit/Utilities/CKComponentActionInternal.h
ComponentKitTests/CKComponentActionTests.mm

Pulling in the templated struct action, we saw an inflation of the binary. Let's try moving some stuff our of the headers to try and reduce some of the bloat.
The curried block function can be implemented fully by users, doesn't need to be present on every template instantiation. Also, move invocation creation and initial configuration to an extern function.

Try to reduce some of the code in the headers of component actions

---

.travis.yml

Not sure why we're whitelisting Travis CI builds. Omitting the whitelist makes it easier for folks to use Travis CI with their own forks.

Do not limit Travis CI builds to master

---

ComponentKit/Utilities/CKComponentAction.mm

According to https://www.mikeash.com/pyblog/friday-qa-2009-03-27-objective-c-message-forwarding.html we missed a step in doing our invocation here. The performSelector:withObject: we were using before looks for a fast-forwarding path if the object doesn't respond to the selector.
We have to make sure that once we get to the responder in the chain that wants the action, we give it the opportunity to forward that selector.

Fix forwarded selectors not respected

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/DataSources/CKCollectionViewTransactionalDataSource.mm
ComponentKit/DataSources/CKComponentBoundsAnimation+UICollectionView.mm
ComponentKit/DataSources/Common/CKComponentDataSourceAttachController.h
ComponentKit/DataSources/Common/CKComponentDataSourceAttachController.mm
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceItem.h
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceItem.mm
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceItemInternal.h
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceChangesetModification.mm
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceReloadModification.mm
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceUpdateConfigurationModification.mm
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceUpdateStateModification.mm
ComponentKitTests/CKComponentDataSourceAttachControllerTests.mm
ComponentKitTests/TransactionalDataSource/CKTransactionalComponentDataSourceChangesetVerificationTests.mm
ComponentKitTests/TransactionalDataSource/CKTransactionalComponentDataSourceStateTestHelpers.mm
ComponentKitTests/TransactionalDataSource/CKTransactionalComponentDataSourceStateTests.mm

In `CKCollectionViewDataSource`, synchronous cell updates do not trigger a collection view reload and instead mount the new component layout in place and animate any size changes. I made this the default behavior for both asynchronous and synchronous updates to `CKCollectionViewTransactionalDataSource`, where the content of the changeset is only cell updates.
Calling `-[UICollectionView reloadItemsAtIndexPaths:]` causes the component to be unmounted and remounted. This is fine in some cases, but it has adverse side effects. It causes the cell to flash to its new state without animation and it also disrupts the first responder.

Add CKComponentBoundsAnimation to CKCollectionViewTransactionalDataSource

---

ComponentKit/Utilities/CKComponentAction.h
ComponentKit/Utilities/CKComponentAction.mm
ComponentKit/Utilities/CKComponentActionInternal.h

I met with @craffert0 this morning to go over strategies to reduce the size of the component action struct because we caused a lot of template bloat due to the tens of thousands of callsites we inflated with the initial templated struct approach. We move the bulk of the implementations to a non-templated base class, and moved the internal struct to be protected, so no more direct access to the value struct! Yay!
We also moved for an explicit external template instantiation for <> and <id> since these are the most common uses, and we can force the compiler to use the out-of-line definition instead of inlining the method bodies. This should make all the callsites just call the same functions in the binary instead of spreading our implementations all over the place.
This shouldn't change any …

Use a base-class for CKTypedComponentAction to reduce size

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/DataSources/CKCollectionViewTransactionalDataSource.mm
ComponentKit/DataSources/CKComponentBoundsAnimation+UICollectionView.mm
ComponentKit/DataSources/Common/CKComponentDataSourceAttachController.h
ComponentKit/DataSources/Common/CKComponentDataSourceAttachController.mm
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceItem.h
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceItem.mm
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceItemInternal.h
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceChangesetModification.mm
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceReloadModification.mm
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceUpdateConfigurationModification.mm
ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceUpdateStateModification.mm
ComponentKitTests/CKComponentDataSourceAttachControllerTests.mm
ComponentKitTests/TransactionalDataSource/CKTransactionalComponentDataSourceChangesetVerificationTests.mm
ComponentKitTests/TransactionalDataSource/CKTransactionalComponentDataSourceStateTestHelpers.mm
ComponentKitTests/TransactionalDataSource/CKTransactionalComponentDataSourceStateTests.mm

#469 was originally reverted by #685 to resolve an internal bounds animation regression. Now that I've spent a bit of time narrowing down the issue we can look into reintroducing these bounds animation changes.
These changes can be merged as-is since they don't introduce the regression. A bad merge internally is to blame and we can handle that fix independently of the OSS contribution.
/cc @conradev

Reintroduce bounds animation changes from #469

---

ComponentKit/Core/CKComponentLifecycleManager.mm
ComponentKit/Debug/CKComponentDebugController.h
ComponentKit/Debug/CKComponentDebugController.mm
ComponentKit/HostingView/CKComponentHostingView.mm
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSource.mm

This was never updated after we transitioned away from `CKComponentLifecycleManager`, so it was mostly broken. Now instead of attempting to use the view hierarchy to trigger reflow, we simply message all interested parties and tell them to update themselves.
Crucially this means that offscreen components are recomputed too, not just onscreen ones. Neat.

Redo how debug "reflow" works

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/Components/CKMemoizingComponent.h
ComponentKit/Components/CKMemoizingComponent.mm
ComponentKit/Core/CKComponent.mm
ComponentKit/Core/CKComponentInternal.h
ComponentKit/Core/CKComponentLifecycleManager.h
ComponentKit/Core/CKComponentLifecycleManager.mm
ComponentKit/Core/CKComponentMemoizer.h
ComponentKit/Core/CKComponentMemoizer.mm
ComponentKit/Core/CKComponentSubclass.h
ComponentKitTests/CKComponentMemoizerTests.mm

My goal here is to reduce the need for customizations to the build and layout calls in every rendering context that wants memoization. Here's an example of what I'm trying to avoid:
https://github.com/facebook/componentkit/pull/675
If your component hierarchy needs memoization, it should work regardless of how you configure your components, and ideally we wouldn't have to do this type of change to every place that builds components.
In this diff I introduce CKMemoizingComponent which prepares the thread-local state for component and layout memoization for its children. This component stores its memoization state into its scope's state.
Due to the nature of the thread-local stack that memoizers are built with, it should be fine to have multiple memoization components in the hierarchy with …

Lift memoization out of core

---

ComponentKit/Utilities/CKComponentAction.h
ComponentKit/Utilities/CKComponentAction.mm
ComponentKit/Utilities/CKComponentActionInternal.h

In inspecting the type encodings of these classes inside the compiled binaries I noted that we're seeing both the CKTypedComponentAction<...> signature AND its sub-struct the CKTypedComponentActionValue struct in the type encoded strings when stored as ivars or passed to obj-c methods. This indirection was made unnecessary by the move to a non-templated base-class, so let's move all this to directly use members of the base-class.
This should change no client code, but should reduce binary bloat a little bit.

Reduce type bloat by removing sub-struct

---

ComponentKit/LayoutComponents/CKRatioLayoutComponent.mm
ComponentKitApplicationTests/CKRatioLayoutComponentTests.mm

Ensure that we always choose a size within the constrainedSize; render to nil for a nil component.

Ratio layout fixes

---

Cartfile.resolved
ComponentKit.xcodeproj/project.pbxproj
ComponentKit/Base/CKAvailability.h
ComponentKit/DataSources/CKComponentBoundsAnimation+UICollectionView.mm
ComponentSnapshotTestCase/CKComponentSnapshotTestCase.h

Today, animating the bounds of a component will crash on pre-iOS 9 environments.
The `supplementaryViewForElementKind:atIndexPath:` selector on
`UICollectionView` [was introduced in iOS 9.](https://developer.apple.com/reference/uikit/uicollectionview/1618041-supplementaryviewforelementkind) However, ComponentKit
targets iOS 8.1+.
`CK_AT_LEAST_IOS9` was only available in the `FBSnapshotTestCase` project so I created `CKAvailability.h`, to avoid duplication.
I sanity checked this fix on device running iOS 8.4.1.

Fix bad UICollectionView selector usage

---

ComponentKit/Core/CKComponent.mm

Knowing the class name of the component and the unexpectedly mounted view should help investigate where these kinds of issues are occurring.

Include component and mounted view class names when logging unexpected view on mount

---

ComponentKit/Core/CKComponentController.h
ComponentKit/StatefulViews/CKStatefulViewComponentController.h
ComponentKitTests/CKComponentActionTests.mm
ComponentKitTests/CKComponentLifecycleManagerTests.mm

API clients won't need to cast self.component to their CKComponent subclass inside CKComponentController subclasses anymore.

Add __covariant to CKComponentController to avoid casting self.component

---

ComponentKit/Core/CKComponentController.mm

In investigating component memory consumption, these ivars were consuming a lot of space, but are relatively rarely used. Move them into a lazily-instantiated wrapper struct.

Move animation ivars into lazy unique_ptr

---

ComponentKit/Core/CKComponent.mm

Follow up to #696. Including the component backtrace aids in debugging this assertion.

Include component backtrace when logging unexpected view on mount

---

ComponentKit/Utilities/CKComponentAction.mm
ComponentKitTests/CKComponentActionTests.mm

If assertions are disabled, or if they log and continue, then the assertion above this call won't stop execution, and we can get to this for loop where the number of arguments in the type signature and the type encodings don't match. In that case we will hard-crash. Let's not crash if that happens.

Fix crash after assertion fire

---

ComponentKit/Utilities/CKComponentAction.mm
ComponentKit/Utilities/CKComponentActionInternal.h
ComponentKitApplicationTests/CKComponentActionAttributeTests.mm

When I updated the actions to use scoped/target actions I forgot to update this. What this means is that the identifier for the action only included the selector, so when a new component mounted we wouldn't update the action registered on the view. That means that old actions were being left on the views, which could cause weird problems. This was fine when we were exclusively responder-chain-based since it would always crawl up from the current component, but no longer. Now we take a reference to the target scope or object.
Fix is simple, just include the pointer value of the action at the time of application. This means that we'll update the value when a new target/selector pair is set.

Correct identifier used in view action attributes

---

ComponentKit/Utilities/CKComponentGestureActions.mm
ComponentKitTests/CKComponentGestureActionsTests.mm

I missed this one yesterday. Identifiers for actions should be built with both the selector and its target, or we risk not installing an updated action attribute when components update and we get a new target.

Fix gesture actions still using selector identifier

---

ComponentKit/StatefulViews/CKStatefulViewComponentController.mm
ComponentKit/StatefulViews/CKStatefulViewReusePool.h
ComponentKit/StatefulViews/CKStatefulViewReusePool.mm
ComponentKitTests/StatefulViews/CKStatefulViewReusePoolTests.mm

This is the counter-proposal to https://github.com/facebook/componentkit/pull/692.
The core idea here is that we introduce a pending reuse pool, and move the dispatch_async hack into the reuse pool. This will allow us to prefer reusing "fully" relinquished views, but will allow fallbacks in the case that no fully relinquished view is present.
This still needs a little bit of work, but here it is.

Pending reuse pool

---

ComponentKit/StatefulViews/CKStatefulViewComponentController.mm
ComponentKit/StatefulViews/CKStatefulViewReusePool.h
ComponentKit/StatefulViews/CKStatefulViewReusePool.mm
ComponentKitTests/StatefulViews/CKStatefulViewReusePoolTests.mm

This reverts commit 42cb8f37f9eecd60c513c3dfc2f2de2bb7b9e522, reversing
changes made to 9df31ebdbd78c8d6b72f48cb93a56738360d1296.
While we're reviewing fixes to stateful views, we decided to revert this diff during the holidays.
Reverts:
https://github.com/facebook/componentkit/pull/693

Revert "Merge pull request #693 from ocrickard/pending-reuse-pool"

---

ComponentKit.xcodeproj/project.pbxproj

Supplements #563, allowing consumers of the framework to implement their own async layers

Expose CKAsyncLayerSubclass and mark it as private

---

ComponentKit/Utilities/CKComponentAction.mm

When not in debug mode this static function was never called. Let's just move the #if to not compile it when it's not called. I built both for debug and release to confirm that the build doesn't break.

Fix unused static function warning

---

static/componentkit.css

remove custom font-weight

---

ComponentKit/Core/CKComponentAnimation.h
ComponentKit/Core/CKComponentAnimation.mm
ComponentKit/Core/CKComponentBacktraceDescription.h
ComponentKit/Core/CKComponentBacktraceDescription.mm
ComponentKit/Core/CKComponentLayout.h
ComponentKit/Core/CKComponentLayout.mm
ComponentKit/Core/CKComponentSize.h
ComponentKit/Core/CKComponentSize.mm
ComponentKit/Core/CKComponentViewAttribute.h
ComponentKit/Core/CKComponentViewAttribute.mm
ComponentKit/Core/CKComponentViewConfiguration.h
ComponentKit/Core/CKComponentViewConfiguration.mm
ComponentKit/Core/CKDimension.h
ComponentKit/Core/CKDimension.mm
ComponentKit/Core/Scope/CKComponentScope.h
ComponentKit/Core/Scope/CKComponentScope.mm
ComponentKit/Core/Scope/CKThreadLocalComponentScope.h
ComponentKit/Core/Scope/CKThreadLocalComponentScope.mm
ComponentKit/Utilities/CKComponentAction.h
ComponentKit/Utilities/CKComponentAction.mm
ComponentKit/Utilities/CKComponentActionInternal.h
ComponentKit/Utilities/CKComponentDelegateAttribute.h
ComponentKit/Utilities/CKComponentDelegateAttribute.mm
ComponentKit/Utilities/CKInternalHelpers.h
ComponentKit/Utilities/CKInternalHelpers.mm

From the first diff in the stack:
Presents a guarantee to the compiler that these functions will not
throw. For reviewers' reference, the consequence of violating a
`noexcept` specification is that `std::terminate` is called.
`NSAssert` seems to throw on error, and `CKAssert` wraps `NSAssert`,
so I considered using `noexcept(!CK_ASSERTIONS_ENABLED)` on those
functions that use `CKAssert`. However, local testing revealed that
`NSAssert` failure in a `noexcept` function doesn't result in an
unusable exception backtrace, at least on Mac. (It doesn't seem to
change the exception crash message at all.)
I did a profile build of WildeGuess for simulator (having difficulty
building for device right now) and observed a 1.4% code size
improvement with this diff, which seems to support my hypothesis …

Add noexcept specifications

---

ComponentKit/Core/CKComponentViewAttribute.h
ComponentKit/Core/CKComponentViewAttribute.mm
ComponentKit/LayoutComponents/CKStackLayoutComponent.h
ComponentKit/LayoutComponents/CKStackLayoutComponent.mm

Doing so prevents instantiations of methods of these templates in every
compilation unit that use them.
These templates were picked empirically based on statistics of which
symbols are duplicated across object files. This reduces the size of
generated static library archives in a large app by 3.6%.
One can examine duplicate symbols in object files by doing something like this:
```
find buck-out/gen -name '*.a' | xargs -L1 objdump -t | grep ' gw ' | grep '__TEXT,__text' | c++filt | cut -f2 |  sort | uniq -c | sort -n
```

Explicitly instantiate some commonly used templates.

---

_docs/14-animation.md

I wrote up some more in-depth documentation on animations. I wanted the top summary section to remain as the quick reference, then provide a deeper dive below.

Add an in-depth section to animations docs

---

ComponentKit/Utilities/CKComponentAction.mm

Running the action is a no-op, so checking the validity of it should be too.

Don't trip debug asserts when the selector of a CKComponentAction is NULL

---

ComponentKit/LayoutComponents/CKBackgroundLayoutComponent.mm
ComponentKit/LayoutComponents/CKOverlayLayoutComponent.mm

Match `CKBackgroundLayoutComponent`, which was already doing the same. Also seize the opportunity for code style cleanup.

CKOverlayLayoutComponent renders to nil if component is nil

---

ComponentKit/Core/Scope/CKDetectComponentScopeCollisions.mm

The additional information will help make it clear which instance of a particular component in the component backtrace is the lowest common ancestor.

Include the memory address of the lowest common ancestor in component scope collisions

---

ComponentKit/Accessibility/CKComponentAccessibility.h
ComponentKit/Accessibility/CKComponentAccessibility.mm

As discussed internally, this change makes it much easier to debug components that use accessibility when inspecting elements on the simulator with the Accessibility Inspector.
**Test Plan:**
- Set breakpoint on `IsAccessibilityEnabled()`
- Run example app in sim, verify that it returns `YES`
- Run example app on device with VoiceOver off, verify that it returns `NO`

Force enable accessibility by default on the simulator

---

ComponentKit/Core/CKDimension.h
ComponentKit/Core/CKDimension.mm

`CKRelativeDimension` and classes which have `CKRelativeDimensions` as fields, such as `CKRelativeSize`, `CKRelativeSizeRange` and `CKComponentSize` especially, are frequently default-constructed (taken to mean "I want everything to be `Auto`"). By making these constructors `constexpr`, they can be evaluated to a compile time constant, and call sites don't need to initialize new instances with Auto/0 in its fields.
Note that for `CKComponentSize` specifically, due to the idiom of using aggregate initialization to generate it, we cannot use the trick of declaring an out-of-line default constructor, as doing so disables aggregate initialization. As a result, a simple `{}` will generate code to inline initialize 6 `CKRelativeDimension` objects. Making `CKRelativeDimension` constructors …

Make default constructor of CKRelativeDimension and friends constexpr

---

ComponentKit/Core/CKComponent.h

One often has to perform a cast when reading back the view from view context like this:
`
FooView *fooView = (FooView *)aComponent.viewContext.view;
`
Adding `__kindof` spares this cast and reduces noise in the code.

[ComponentKit] Add __kindof for CKComponentViewContext

---

ComponentKit/Components/CKNetworkImageComponent.h
ComponentKit/Components/CKNetworkImageComponent.mm
ComponentKit/Components/CKNetworkImageDownloading.h
ComponentKitApplicationTests/CKNetworkImageComponentTests.mm

codemod -m --extensions h,m,mm 'scenePath'
and one by one removed all the instances of this signature
This is an API breaking change.
Tested in Xcode CMD-U.

removed unused scenePath object from CK signatures

---

ComponentKit/Base/CKMacros.h

This can be done at compile time with the `objc_subclassing_restricted` attribute.

Remove unused CK_FINAL_CLASS

---

ComponentKit/TransactionalDataSources/Common/Internal/CKTransactionalComponentDataSourceChangesetVerification.mm
ComponentKitTests/TransactionalDataSource/CKTransactionalComponentDataSourceChangesetVerificationTests.mm

Here is an example of what this diff is fixing. Consider a list being updated from `[A, B, C, D]` to `[D, A]`.
The changeset would be `[delete(from:[1,2]), move(from:3, to:0)]`.
Because this algorithm apply these changes in place with move handled in the last, at the time when moves are being verified, index 3 no longer exists.
The fix is to keep a copy of the original state and always verify fromIndexPath or fromSection with that.

Fix changeset verification with a move whose original index path is non-existent after update

---

ComponentKit/Utilities/CKComponentAction.mm
ComponentKitTests/CKComponentActionTests.mm

So what happened here is that we added targetForAction:withSender: to CKComponents which is part of the UIResponder API, but when I made it possible to use non-CKComponents or responders as the target, I didn't catch that targetForAction:withSender: can't be called blindly.
This was working without crashing because I was testing it against views and view controllers, which subclass UIResponder and implement this method.

Fix blind call to targetForAction:withSender:

---

ComponentKitTests/TransactionalDataSource/CKTransactionalComponentDataSourceChangesetModificationTests.mm

Add another test case to cover a move related edge case, the same case that I fixed in https://github.com/facebook/componentkit/pull/767 for the verification algorithm.

Add more test related to move to CKTransactionalComponentDataSourceChangesetModificationTests

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/ComponentKit.h
ComponentKit/Components/CKButtonComponent.h
ComponentKit/Components/CKButtonComponent.mm
ComponentKit/Core/CKComponentViewConfiguration.h
ComponentKit/Core/CKComponentViewConfiguration.mm
ComponentKit/LayoutComponents/CKStackLayoutComponent.h
ComponentKit/LayoutComponents/CKStackLayoutComponent.mm
ComponentKit/LayoutComponents/CKStaticLayoutComponent.h
ComponentKit/LayoutComponents/CKStaticLayoutComponent.mm
ComponentKit/Utilities/CKContainerWrapper.h

ComponentKit frequently uses Objective C++ methods that takes in lists as parameters. These parameters are usually declared as `const std::vector<Foo> &`. This is suboptimal for two reasons:
1. In cases where the parameters specified as an initializer list, this initializer list must be converted into a vector before being passed into this method. This incurs a (potentially inlined) vector construction and destruction operation that bloats the binary.
2. In cases where the parameter is passed in as a pre-constructed vector and stored, it must be copied due to the incoming vector being a mere const reference.
This change introduces `CKContainerWrapper`, which can be used as a drop-in replacement for methods which currently takes in `const vector<T> &`, but will not (in my testing at least) …

Avoid inline construction of vector in parameter lists

---

_docs/04-component-api.md

We only expose `layoutThatFits:parentSize` in `CKComponentSubclass`, not on the base object. Removing it from the docs.

Remove -layoutThatFits:parentSize from Docs.

---

ComponentKit/Utilities/CKComponentAction.mm
ComponentKit/Utilities/CKComponentActionInternal.h

The old layout involved two weak objc pointers, so the resulting destructor needs to call `objc_destroyWeak` twice (and associated offset calculations to find the fields). Since these objects are constructed (and destroyed) often, the inlined destruction cost is noticeable.
Since only one of the two weak fields are ever populated, I collapsed them into a single field, and use the enum to interpret it. I also moved the field to the start of the object so that no offset calculation is necessary. This makes the destructor effectively a single `objc_destroyWeak` call. I leave this inline-able since nothing would be gained by forcing another function call.
Here's an example of the destructor portion of the generated code of a function that creates 3 of these temporaries to pass to another …

Tweak object layout of CKTypedComponentActionBase to reduce code size

---

ComponentKit/Accessibility/CKComponentAccessibility.h
ComponentKit/Accessibility/CKComponentAccessibility.mm

This was reverted internally, so revert it here to maintain consistency.

Revert "Merge pull request #760 from indragiek/sim-accessibility"

---

ComponentKit/Utilities/CKComponentGestureActions.mm
ComponentKitTests/CKComponentGestureActionsTests.mm

It solves #622.
I went with solution number 1, because in this case it's quite effective.
Adding 2 new lifecycle blocks for attributes (solution 2) is, for me, not the way to go because interactions between applicator, unapplicator, updater, and the new blocks will be quite complex. (glad to be proven wrong on this)
Another approach that I would follow is to create a subclass (substruct??) of CKComponentViewAttribute (maybe CKComponentViewAttributeUnmountRemovable) that can is removed at unmount not when the view is remounted.
I cannot see any other obvious attribute that would benefit of this procedure (that's why it's more a proposal and i have not implemented), but if we found any other we should think about what's the best approach.
Please let me know what do you think about it.

CKGestureAction will not fire if the view has a nil ck_component

---

ComponentKit/Core/CKComponentInternal.h

Fixes https://github.com/facebook/componentkit/issues/621. This comment is simply incorrect. Unapplication occurs on *mounting* not on *unmounting*. I'm open to moving this comment, but couldn't think of a good place to put it.

Remove incorrect comment for unmounting

---

ComponentKit/HostingView/CKComponentHostingView.h
ComponentKit/HostingView/CKComponentHostingView.mm

Currently appearance callbacks (`componentTreeWillAppear` and `componentTreeDidDisappear`) on the component controller are not called when a component is hosted in a hosting view. This change provides a way for users to explicitly trigger appearance events on the hosting view, which will then be funneled to the component controller.
This has to be done manually since there is no easy way to infer the visibility change of a view (there are so many factors like alpha value of ancestor, covered by other views etc)

Add appearance API on hosting views

---

ComponentKit/Utilities/CKComponentAction.h
ComponentKit/Utilities/CKComponentAction.mm
ComponentKitTests/CKComponentActionTests.mm
ComponentKitTests/CKComponentDataSourceAttachControllerTests.mm
ComponentKitTests/CKComponentDelegateAttributeTests.mm

This commit was landed/reverted, so our bot had trouble importing the updated/accepted diff. Putting up a clean patch to make it happy.
For previous info, see https://github.com/facebook/componentkit/pull/786

Remove assert, make actions no-op when they have no target or selector.

---

ComponentKit/Core/Scope/CKDetectComponentScopeCollisions.mm

It isn't obvious what the impact of a scope collision is based on the language used in the error. I've updated the error's description to be a bit firmer in language, describing the possibility of strange and unexpected behavior (along with some simple, yet actionable, next steps).

Use firmer language when describing scope collisions

---

ComponentKit/Utilities/CKComponentAction.h
ComponentKit/Utilities/CKComponentAction.mm
ComponentKit/Utilities/CKComponentActionInternal.h
ComponentKitTests/CKComponentActionTests.mm
Examples/WildeGuess/WildeGuess/Components/InteractiveQuoteComponent.mm

We originally had an interface like this for JS interop, but we removed it due to binary size. Let's try adding this back and see what it does since @ashwinb needs this for JS interop in CK.
This is a test diff to see binary size impact. I'm mostly concerned about additional objc_storeStrong in every receiving callsite of a component action.
BTW, using templates we can actually handle the block promotion/demotion relatively nicely, since each time the block is converted, we know the number of arguments before/after so we can wrap the blocks with a new template pack.... however at the cost of additional code bloat at the conversion callsites, and unlike selectors when promoting/demoting we actually slice off the values as you convert.
Thus, I think it's probably safer/better in the …

Add a block interface for actions

---

ComponentKit/Utilities/CKComponentAction.h

I used is_trivially_constructible, but really what we need here are things that work with NSInvocation. dispatch blocks should be totally fine to pass to NSInvocation, it has fully support in the language. Yet, is_trivially_constructible returns the false type.
This allows CKTypedComponentAction<dispatch_block_t>, but still forbids CKTypedComponentAction<std::vector<int>>, since that would result in undefined behavior when calling the method with a complex type. We allow references, pointers, things that convert to id, and trivially constructible types.

Trivial blocks

---

ComponentKit.xcodeproj/project.pbxproj
ComponentKit/Core/Scope/CKComponentKey.h
ComponentKit/Core/Scope/CKComponentKey.mm
ComponentKit/Core/Scope/CKComponentKeyStorage.h
ComponentKit/Core/Scope/CKComponentKeyStorage.mm
ComponentKit/Core/Scope/CKComponentScope.h
ComponentKit/Core/Scope/CKComponentScope.mm
ComponentKit/Core/Scope/CKComponentScopeFrame.h
ComponentKit/Core/Scope/CKComponentScopeFrame.mm
ComponentKitTests/Scope/CKComponentKeyTests.mm

We want the ability for parents to assign keys to their children, instead of requiring children to assign keys to themselves using `CKComponentScope`. The new `CKComponentKey` struct allows doing this.
Example usage:
```
[CKStackLayoutComponent
newWithChildren:CK::map(models, ^(XXPerson *person) {
CKComponenentKey key(person.uniqueIdentifier);
return [XXPersonComponent newWithPerson:person];
}]
```

CKComponentKey: allow parents to assign keys to children

---

ComponentKit/Components/CKButtonComponent.mm
ComponentKit/Utilities/CKComponentAction.h
ComponentKit/Utilities/CKComponentGestureActions.mm
ComponentKitApplicationTests/CKComponentActionAttributeTests.mm
ComponentKitTests/CKComponentAccessibilityCustomActionsAttributeTests.mm
ComponentKitTests/CKComponentGestureActionsTests.mm
ComponentKitTests/CKOptimisticViewMutationsTests.mm

* `NULL` can possibly be `0`, `0L`, or `nullptr_t`, depending on implementation or whether using C or C++.
* `CKTypedComponentAction` has multiple constructors which accept one parameter:
* `SEL`: essentially `char *`, which is pointer-sized
* `int`: probably pointer sized
* `long`: pointer sized
* `dispatch_block_t`: IIRC, either an object (Obj-C) or a lambda (C++).
* `std::nullptr_t`: typesafe `NULL`
A `NULL` result in a ternary expression that provides a value to a struct with a `CKTypedComponentAction<CKComponent *>` field is seemingly allowed by clang but may result in undefined behavior.
Basically: the ternary was supposed to return a `CKTypedComponentAction<CKComponent *>`, i.e. a value, not a pointer. Sensibly, the non-`NULL` case calls the copy constructor, so it makes sense that …

Remove int+long CKTypedComponentAction constructors

---

ComponentTextKit/TextKit/CKTextKitRenderer.mm

This attempts to fix #809. Not entirely sure if there could be any side effects in exchange for a performance boost… but all the tests pass! ¯\_(ツ)_/¯

[ComponentTextKit] Optimize TextKit Renderer to Only Draw Supplied Bounds

---

ComponentKit/Utilities/CKComponentActionInternal.h

Whelp, it turns out that when we moved this to NSInvocation, we stopped retaining the target of the action during the scope of the call. When I refactored scopes recently, I inadvertently weakified the only remaining strong references of some components internally, and this started firing.
Within the scope of the action call, the component can do anything... and one of the primary things that is done is updateState:. In truly synchronous (aka not transactional datasource updates) updates, that means that the component can actually be deallocated within the invocation! This causes the component itself to no longer be a valid object within the scope of one of its methods. This means any dereferences, etc. become undefined, and can crash with EXC_BAD_ACCESS.
So this diff returns the action …

Fix memory management of actions

---

ComponentKit/Core/Scope/CKComponentScopeFrame.h
ComponentKit/Core/Scope/CKComponentScopeFrame.mm

Now that we have `CKScopedComponent` this assert will falsely fire. Removing.

Remove CKComponent class assertion in CKComponentScopeFrame.

---

ComponentKit/Core/Scope/CKThreadLocalComponentScope.h
ComponentKit/Core/Scope/CKThreadLocalComponentScope.mm
ComponentKitTests/Scope/CKComponentScopeTests.mm

If another `CKThreadLocalComponentScope` is created while another is in scope, it is overridden. This changes behavior so that the newly created scope takes precedence as `currentScope` for the duration of its' lifecycle. When it is destructed, the previous `currentScope` is restored.

Introduce concept of nested thread local scopes.

---

ComponentKit/Core/CKComponentAnimation.mm
ComponentKit/Core/CKComponentInternal.h
ComponentKit/Core/CKComponentSubclass.h

`-[CKComponent viewForAnimation]` and `-[CKCompositeComponent viewForAnimation]` can, and often are, used to support more complex animations in a component hierarchy. Given this reality move the declaration of this method out of `CKComponentInternal.h` and into `CKComponentSubclass.h`.

Allow component subclasses to obtain a reference to the view used to render animations

---

ComponentKit/Core/CKComponentViewConfiguration.mm

This should help avoiding silly bugs like the one I had when I passed a `XComponent` instead instead of `XComponentView`.
I couldn't figure out if there's an earlier point where we can to assert on the `viewClass`?

Check viewClass being a subclass of a UIView

---

ComponentKit/Core/Scope/CKComponentScopeHandle.h
ComponentKit/Core/Scope/CKComponentScopeHandle.mm
ComponentKit/Utilities/CKComponentAction.mm
ComponentKitTests/CKComponentActionTests.mm

We are seeing a problem in the Facebook app because Scoped Component Actions that use the same selector are overriding each other within `CKComponentAttributeValueMap`. This fixes that!

Fix Scoped Component Actions so that they have unique identifiers.

---

ComponentKit/Core/Scope/CKComponentScopeHandle.mm

Great idea by @ocrickard. Instead of creating a responder when a handle with a new identifier is created, we wait until the first time someone requests a responder.
I tested this in News Feed, and it reduced the number of allocations by 8-10x (depending on the content in feed). Woot!

Only create a scoped responder the first time we need it.

---

ComponentKit/Base/CKAssert.h
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSource.mm
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceConfiguration.mm
ComponentKit/TransactionalDataSources/Common/CKTransactionalComponentDataSourceConfigurationInternal.h
ComponentKit/Utilities/CKBadChangesetOperationType.mm

This pull request essentially reverts #755, though it allows us to internally map invalid changeset assertions to crashes for employees only.
The gist of these changes is pretty straightforward: introduce a new flavor of `CKAssert`/`CKCAssert` for "fatal" assertions. Externally`CKFatalAssert` and `CKCFatalAssert` act just like `NSAssert` and `NSCAssert`, respectively. Differentiating `CKAssert` and `CKFatalAssert` allows us to rely on internal tools to help us collect a bit more debugging information for employee-only builds.

Introduce the concept of fatal assertions and use them when encountering invalid changesets

---

build.sh

I guess Travis CI replaced the iOS 10.3 simulator with 10.3.1?

Upgrade the iOS version to fix Travis CI

---

ComponentKit/Core/CKComponentLayout.h
ComponentKit/Core/CKComponentLayout.mm

No reason to do a bunch of mallocs to get const empty vectors.

CKComponentLayout: cache empty vector of children

---

ComponentKit/Core/Scope/CKComponentScopeHandle.h
ComponentKit/Core/Scope/CKComponentScopeHandle.mm
ComponentKit/Utilities/CKComponentAction.mm
ComponentKit/Utilities/CKComponentActionInternal.h

We are seeing an issue where old component generations are still being kept around (whether from retain cycle, or some funny client code) that is causing us to choose an responder that is incorrect.
Here's a scenario:
Within `CKScopedResponder` we keep a vector of `__weak CKComponentScopeHandle *`
In the event an old component generation wasn't dealloced. We could see something like this:
```
{ ScopeHandleA, nil, nil, nil, nil, nil ScopeHandleF, ScopeHandleG }
```
Currently, we simply choose the oldest handle as a responder (`ScopeHandleA`), when in reality, we want `ScopeHandleF`.
Now, when we create a `CKComponentAction` we store a bookmark to the oldest possible component we would want to look at. So, after this commit lands we would create an action that says, "Give me the oldest …

Prevent Scoped Responder from returning an old component that is still alive.

---

ComponentKit/Utilities/CKComponentGestureActions.mm
ComponentKitTests/CKComponentGestureActionsTests.mm

If you pass `Nil` for the gesture recognizer class, we should gracefully do nothing instead of crashing the app entirely. (`UIView addGestureRecognizer:` crashes with a nil input.)

Gracefully handle a nil gesture recognizer class

---

ComponentKit/Utilities/CKComponentAction.mm
ComponentKitTests/CKComponentActionTests.mm

Equality was broken, this is causing some bad stuff to happen. Fix, commented, and added equality tests for all component action types.

Fix Scoped Action Equality. Add Equality tests for all action types.

---

ComponentKit/Core/Scope/CKComponentScopeRoot.h
ComponentKit/Core/Scope/CKComponentScopeTypes.h

- 'CKComponentScopeRoot' will conform to this protocol.
- The protocol extracts the enumration over predicates methods from 'CKComponentScopeRoot'.
- This way we can leverage these methods without exposing the internal implementation of 'CKComponentScopeRoot'.

Introduce the 'CKComponentScopeEnumeratorProvider' protocol.

---

ComponentKit/HostingView/CKComponentHostingView.mm
ComponentKit/HostingView/CKComponentHostingViewInternal.h

Now that the scope root conforms to the new 'CKComponentScopeEnumeratorProvider' protocol , we are adding an access to the enumerator from 'CKComponentHostingView'.

Expose the scope enumerator provider in CKComponentHostingView.mm

---

ComponentKit/Components/CKButtonComponent.mm
ComponentKit/Utilities/CKComponentAction.h
ComponentKitTests/CKComponentActionTests.mm

Previously demoting an object would call `CKTypedComponentAction<>(const CKTypedComponentAction<T...>&)` and error if the supplied action was a block. This provides a safe way to demote via currying.
Test added to demonstrate that demoting works as expected.

Add ability to demote CKTypedComponentAction, use it in CKButtonComponent

---

ComponentKit/Utilities/CKComponentAction.mm
ComponentKitTests/CKComponentActionTests.mm

The invariant is that if two CKComponentActions are not equal (according to `operator==`) they must have distinct identifiers. This was not true for block-based actions. Make it so.

Fix bug with block-based CKComponentActions

---

ComponentKit/Utilities/CKComponentAction.h
ComponentKit/Utilities/CKComponentAction.mm
ComponentKitApplicationTests/CKComponentActionAttributeTests.mm

This was broken with #848. This fixes the bug and adds a test for the broken behavior.

Fix bug with CKComponentActions and UIControls

---

_docs/12-component-controllers.md

example code in this chapter is wrong. 
which `+ (Class<CKComponentControllerProtocol>)controllerClass` should be implemented in subclass of `CKCompositeComponent`

FIX: wrong code in `component controllers`

---

_docs/08-responder-chain.md

The original [link](https://developer.apple.com/library/ios/documentation/EventHandling/Conceptual/EventHandlingiPhoneOS/event_delivery_responder_chain/event_delivery_responder_chain.htm) seems to no longer exist and takes users to an overview of UIKit.
After some digging, I found a more appropriate [link](https://developer.apple.com/documentation/uikit/touches_presses_and_gestures/using_responders_and_the_responder_chain_to_handle_events) for the Responder Chain

Update Responder Chain documentation link

---

_docs/06-views.md

As I understand it, CKStackLayoutComponent is deprecated in favor of CKFlexboxComponent. Thus the change.

Replaced CKStackLayoutComponent with CKFlexboxComponent.

---

ComponentKit/Core/CKComponentGenerator.mm
ComponentKit/DataSources/CKCollectionViewDataSource.mm
ComponentKit/DataSources/CKComponentBoundsAnimation+UICollectionView.mm
ComponentKit/HostingView/CKComponentHostingView.mm
ComponentKit/StatefulViews/CKStatefulViewReusePool.mm
ComponentKit/TransactionalDataSources/Common/CKDataSource.mm
ComponentKit/TransactionalDataSources/Common/CKDataSourceChangesetApplicator.mm
ComponentKit/TransactionalDataSources/Common/Internal/CKDataSourceChangesetModification.mm
ComponentKit/TransactionalDataSources/Common/Internal/CKDataSourceSplitChangesetModification.mm
ComponentTextKit/TextKit/CKTextKitTailTruncater.mm
ComponentTextKit/Utility/CKAsyncLayer.mm
ComponentTextKit/Utility/CKAsyncTransaction.mm
RenderCore/Base/CKOptional.h

The clang-14 in Xcode 14 introduces a bunch of new errors including many
missing `self->` and a couple missing copy-assignment/copy-constructors.
Fix them all here so that WildeGuess builds with Xcode14.

Fix a bunch of issues from the Xcode 14 upgrade
